/**
 * Author:  Napoleon Avila Ochoa
 * Created: 04/12/2025
 */
DROP TABLE IF EXISTS BOOK;
DROP TABLE IF EXISTS EDITORIAL;

CREATE TABLE IF NOT EXISTS EDITORIAL (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL,
    ADDRESS VARCHAR(255),
    MAXIMUM_BOOKS INT NOT NULL DEFAULT -1,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    EMAIL VARCHAR(100)
);
CREATE TABLE IF NOT EXISTS BOOK (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    EDITORIAL_ID INT NOT NULL,
    TITLE VARCHAR(255) NOT NULL,
    AUTHOR VARCHAR(255) NOT NULL,
    GENRE VARCHAR(150) NOT NULL,
    PAGES INT NOT NULL DEFAULT 1,
    ACTIVE BOOLEAN DEFAULT TRUE NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    PUBLICATION_YEAR INT,
    FOREIGN KEY (EDITORIAL_ID) REFERENCES EDITORIAL(ID) ON DELETE CASCADE
);

-- Inserts para la tabla EDITORIAL
INSERT INTO EDITORIAL (NAME, ADDRESS, EMAIL, MAXIMUM_BOOKS) VALUES
('Penguin Random House', 'Travessera de Gràcia 47-49, Barcelona', 'info@penguinrandomhouse.com', 5000),
('Editorial Planeta', 'Av. Diagonal 662-664, Barcelona', 'contacto@planeta.es', 4500),
('Anagrama', 'Carrer de Pedró i Pons 9, Barcelona', 'editorial@anagrama-ed.es', 2000),
('Alfaguara', 'Calle Torrelaguna 60, Madrid', 'info@alfaguara.es', 3500),
('Tusquets Editores', 'Carrer del Consell de Cent 425, Barcelona', 'tusquets@tusquetseditores.com', 2500),
('Editorial Anaya', 'Calle Juan Ignacio Luca de Tena 15, Madrid', 'anaya@anaya.es', 3000),
('Ediciones SM', 'Calle Impresores 2, Madrid', 'contacto@grupo-sm.com', 2800),
('Editorial Santillana', 'Av. de los Artesanos 6, Madrid', 'info@santillana.com', 4000),
('Espasa', 'Av. Diagonal 662, Barcelona', 'espasa@espasa.es', 2200),
('Ediciones B', 'Carrer de Bailén 84, Barcelona', 'info@edicionesb.com', 1800),
('RBA Libros', 'Diagonal 189, Barcelona', 'info@rba.es', 2600),
('Alianza Editorial', 'Calle Juan Ignacio Luca de Tena 15, Madrid', 'alianza@alianzaeditorial.es', 3200),
('Seix Barral', 'Av. Diagonal 662-664, Barcelona', 'seixbarral@planeta.es', 1900),
('Debate', 'Travessera de Gràcia 47-49, Barcelona', 'debate@penguinrandomhouse.com', 1600),
('Salamandra', 'Carrer de Mallorca 237, Barcelona', 'info@salamandra.info', 1400),
('Ediciones Destino', 'Av. Diagonal 662-664, Barcelona', 'destino@planeta.es', 2100),
('Grijalbo', 'Travessera de Gràcia 47-49, Barcelona', 'grijalbo@penguinrandomhouse.com', 2300),
('Círculo de Lectores', 'Travessera de Gràcia 47-49, Barcelona', 'info@circulo.es', 1700),
('Ediciones Cátedra', 'Calle Rufino González 26, Madrid', 'catedra@catedra.com', 2000),
('Editorial Crítica', 'Av. Diagonal 662-664, Barcelona', 'critica@planetadelibros.com', 1500),
('Paidós', 'Av. Diagonal 662-664, Barcelona', 'paidos@paidos.com', 1800),
('Ariel', 'Av. Diagonal 662-664, Barcelona', 'ariel@ariel.es', 1600),
('Taurus', 'Calle Torrelaguna 60, Madrid', 'taurus@santillana.com', 1900),
('Plataforma Editorial', 'Calle Muntaner 231-233, Barcelona', 'info@plataformaeditorial.com', 1200),
('Blackie Books', 'Carrer de la Diputació 260, Barcelona', 'hola@blackiebooks.org', 800),
('Nórdica Libros', 'Calle del Doctor Fourquet 27, Madrid', 'info@nordicalibros.com', 600),
('Páginas de Espuma', 'Calle de Madera 3, Madrid', 'info@paginasdeespuma.com', 500),
('Pre-Textos', 'Calle Luis Santángel 10, Valencia', 'pretextos@pre-textos.com', 700),
('Editorial Acantilado', 'Carrer de la Quadra 1, Barcelona', 'acantilado@acantilado.es', 900),
('Impedimenta', 'Calle de Benito Gutiérrez 26, Madrid', 'info@impedimenta.es', 650),
('Sexto Piso', 'Calle de Monte Alegre 21, Madrid', 'info@sextopiso.com', 550),
('Libros del Asteroide', 'Carrer de Padilla 234, Barcelona', 'info@librosdelasteroide.com', 750),
('Galaxia Gutenberg', 'Av. Diagonal 361, Barcelona', 'info@galaxiagutenberg.com', 1100),
('Ediciones Siruela', 'Calle de Almagro 25, Madrid', 'siruela@siruela.com', 1300),
('Minúscula', 'Carrer del Rosselló 230, Barcelona', 'editorial@minuscula.com', 400),
('Navona Editorial', 'Calle Hermosilla 104, Madrid', 'info@navonaeditorial.com', 850),
('Ediciones Obelisco', 'Carrer de Pere IV 78, Barcelona', 'info@edicionesobelisco.com', 950),
('Editorial Almuzara', 'Parque Logístico de Córdoba, Córdoba', 'almuzara@almuzaralibros.com', 1050),
('Ediciones Edhasa', 'Av. Diagonal 519-521, Barcelona', 'info@edhasa.es', 1150),
('Errata Naturae', 'Calle del Doctor Fourquet 11, Madrid', 'info@erratanaturae.com', 450),
('Funambulista', 'Calle de Nicasio Gallego 2, Madrid', 'info@funambulista.net', 500),
('Editorial Periférica', 'Calle del Apdo 240, Cáceres', 'info@editorialperiferica.com', 550),
('Caballo de Troya', 'Travessera de Gràcia 47-49, Barcelona', 'info@caballodetroya.es', 1000),
('Duomo Ediciones', 'Av. del Parc Logístic 12-20, Barcelona', 'info@duomoediciones.com', 1250),
('Punto de Lectura', 'Calle Torrelaguna 60, Madrid', 'info@puntodelectura.com', 1400),
('Editorial Kalandraka', 'Rúa de Pastor Díaz s/n, Pontevedra', 'kalandraka@kalandraka.com', 800),
('Ediciones Maeva', 'Calle de Benito Castro 6, Madrid', 'maeva@maeva.es', 900),
('Editorial Bruño', 'Calle Valentín Beato 21, Madrid', 'bruno@editorial-bruno.es', 1600),
('Edelvives', 'Carretera de Madrid km 315,7, Zaragoza', 'edelvives@edelvives.es', 1800),
('La Esfera de los Libros', 'Av. Alfonso XIII 1, Madrid', 'info@esferalibros.com', 1300);

-- Inserts para la tabla BOOK
INSERT INTO BOOK (EDITORIAL_ID, TITLE, AUTHOR, GENRE, PAGES, ACTIVE, PUBLICATION_YEAR) VALUES
((SELECT ID FROM EDITORIAL WHERE NAME = 'Penguin Random House'), 'Cien años de soledad', 'Gabriel García Márquez', 'Realismo mágico', 471, TRUE, 1967),
((SELECT ID FROM EDITORIAL WHERE NAME = 'Penguin Random House'), 'El amor en los tiempos del cólera', 'Gabriel García Márquez', 'Romance', 368, TRUE, 1985),
((SELECT ID FROM EDITORIAL WHERE NAME = 'Editorial Planeta'), 'La sombra del viento', 'Carlos Ruiz Zafón', 'Misterio', 576, TRUE, 2001),
((SELECT ID FROM EDITORIAL WHERE NAME = 'Editorial Planeta'), 'Marina', 'Carlos Ruiz Zafón', 'Misterio', 312, TRUE, 1999),
((SELECT ID FROM EDITORIAL WHERE NAME = 'Anagrama'), 'Soldados de Salamina', 'Javier Cercas', 'Ficción histórica', 215, TRUE, 2001),
((SELECT ID FROM EDITORIAL WHERE NAME = 'Anagrama'), 'El impostor', 'Javier Cercas', 'Ficción', 432, TRUE, 2014),
((SELECT ID FROM EDITORIAL WHERE NAME = 'Alfaguara'), 'La casa de los espíritus', 'Isabel Allende', 'Realismo mágico', 433, TRUE, 1982),
((SELECT ID FROM EDITORIAL WHERE NAME = 'Alfaguara'), 'Paula', 'Isabel Allende', 'Autobiografía', 368, TRUE, 1994),
((SELECT ID FROM EDITORIAL WHERE NAME = 'Tusquets Editores'), 'El juego del ángel', 'Carlos Ruiz Zafón', 'Misterio', 672, TRUE, 2008),
((SELECT ID FROM EDITORIAL WHERE NAME = 'Tusquets Editores'), 'Rayuela', 'Julio Cortázar', 'Ficción experimental', 736, TRUE, 1963),
((SELECT ID FROM EDITORIAL WHERE NAME = 'Editorial Anaya'), 'Don Quijote de la Mancha', 'Miguel de Cervantes', 'Clásico', 863, TRUE, 1605),
((SELECT ID FROM EDITORIAL WHERE NAME = 'Editorial Anaya'), 'La Celestina', 'Fernando de Rojas', 'Clásico', 288, TRUE, 1499),
((SELECT ID FROM EDITORIAL WHERE NAME = 'Ediciones SM'), 'El principito', 'Antoine de Saint-Exupéry', 'Infantil', 96, TRUE, 1943),
((SELECT ID FROM EDITORIAL WHERE NAME = 'Ediciones SM'), 'Harry Potter y la piedra filosofal', 'J.K. Rowling', 'Fantasía', 254, TRUE, 1997),
((SELECT ID FROM EDITORIAL WHERE NAME = 'Editorial Santillana'), 'El código Da Vinci', 'Dan Brown', 'Thriller', 489, TRUE, 2003),
((SELECT ID FROM EDITORIAL WHERE NAME = 'Editorial Santillana'), 'Ángeles y demonios', 'Dan Brown', 'Thriller', 616, TRUE, 2000),
((SELECT ID FROM EDITORIAL WHERE NAME = 'Espasa'), 'La Regenta', 'Leopoldo Alas Clarín', 'Clásico', 789, TRUE, 1884),
((SELECT ID FROM EDITORIAL WHERE NAME = 'Espasa'), 'Fortunata y Jacinta', 'Benito Pérez Galdós', 'Clásico', 1056, TRUE, 1887),
((SELECT ID FROM EDITORIAL WHERE NAME = 'Ediciones B'), 'El tiempo entre costuras', 'María Dueñas', 'Ficción histórica', 608, TRUE, 2009),
((SELECT ID FROM EDITORIAL WHERE NAME = 'Ediciones B'), 'La templanza', 'María Dueñas', 'Ficción histórica', 688, TRUE, 2015),
((SELECT ID FROM EDITORIAL WHERE NAME = 'RBA Libros'), 'Los pilares de la Tierra', 'Ken Follett', 'Ficción histórica', 1008, TRUE, 1989),
((SELECT ID FROM EDITORIAL WHERE NAME = 'RBA Libros'), 'Un mundo sin fin', 'Ken Follett', 'Ficción histórica', 1120, TRUE, 2007),
((SELECT ID FROM EDITORIAL WHERE NAME = 'Alianza Editorial'), 'El nombre de la rosa', 'Umberto Eco', 'Misterio histórico', 536, TRUE, 1980),
((SELECT ID FROM EDITORIAL WHERE NAME = 'Alianza Editorial'), 'El péndulo de Foucault', 'Umberto Eco', 'Ficción', 656, TRUE, 1988),
((SELECT ID FROM EDITORIAL WHERE NAME = 'Seix Barral'), 'La catedral del mar', 'Ildefonso Falcones', 'Ficción histórica', 672, TRUE, 2006),
((SELECT ID FROM EDITORIAL WHERE NAME = 'Seix Barral'), 'Los herederos de la tierra', 'Ildefonso Falcones', 'Ficción histórica', 768, TRUE, 2016),
((SELECT ID FROM EDITORIAL WHERE NAME = 'Debate'), 'El silencio de los corderos', 'Thomas Harris', 'Thriller', 352, TRUE, 1988),
((SELECT ID FROM EDITORIAL WHERE NAME = 'Debate'), 'Hannibal', 'Thomas Harris', 'Thriller', 486, TRUE, 1999),
((SELECT ID FROM EDITORIAL WHERE NAME = 'Salamandra'), 'La insoportable levedad del ser', 'Milan Kundera', 'Ficción filosófica', 320, TRUE, 1984),
((SELECT ID FROM EDITORIAL WHERE NAME = 'Salamandra'), 'La broma', 'Milan Kundera', 'Ficción', 352, TRUE, 1967),
((SELECT ID FROM EDITORIAL WHERE NAME = 'Ediciones Destino'), '1984', 'George Orwell', 'Distopía', 328, TRUE, 1949),
((SELECT ID FROM EDITORIAL WHERE NAME = 'Ediciones Destino'), 'Rebelión en la granja', 'George Orwell', 'Fábula política', 152, TRUE, 1945),
((SELECT ID FROM EDITORIAL WHERE NAME = 'Grijalbo'), 'El guardián entre el centeno', 'J.D. Salinger', 'Ficción', 277, TRUE, 1951),
((SELECT ID FROM EDITORIAL WHERE NAME = 'Grijalbo'), 'Franny y Zooey', 'J.D. Salinger', 'Ficción', 201, TRUE, 1961),
((SELECT ID FROM EDITORIAL WHERE NAME = 'Círculo de Lectores'), 'Crónica de una muerte anunciada', 'Gabriel García Márquez', 'Ficción', 120, TRUE, 1981),
((SELECT ID FROM EDITORIAL WHERE NAME = 'Círculo de Lectores'), 'El coronel no tiene quien le escriba', 'Gabriel García Márquez', 'Ficción', 104, TRUE, 1961),
((SELECT ID FROM EDITORIAL WHERE NAME = 'Ediciones Cátedra'), 'La colmena', 'Camilo José Cela', 'Realismo social', 336, TRUE, 1951),
((SELECT ID FROM EDITORIAL WHERE NAME = 'Ediciones Cátedra'), 'La familia de Pascual Duarte', 'Camilo José Cela', 'Tremendismo', 168, TRUE, 1942),
((SELECT ID FROM EDITORIAL WHERE NAME = 'Editorial Crítica'), 'El túnel', 'Ernesto Sabato', 'Ficción psicológica', 158, TRUE, 1948),
((SELECT ID FROM EDITORIAL WHERE NAME = 'Editorial Crítica'), 'Sobre héroes y tumbas', 'Ernesto Sabato', 'Ficción', 528, TRUE, 1961),
((SELECT ID FROM EDITORIAL WHERE NAME = 'Paidós'), 'Pedro Páramo', 'Juan Rulfo', 'Realismo mágico', 124, TRUE, 1955),
((SELECT ID FROM EDITORIAL WHERE NAME = 'Paidós'), 'El llano en llamas', 'Juan Rulfo', 'Cuentos', 168, TRUE, 1953),
((SELECT ID FROM EDITORIAL WHERE NAME = 'Ariel'), 'Ficciones', 'Jorge Luis Borges', 'Cuentos', 174, TRUE, 1944),
((SELECT ID FROM EDITORIAL WHERE NAME = 'Ariel'), 'El Aleph', 'Jorge Luis Borges', 'Cuentos', 203, TRUE, 1949),
((SELECT ID FROM EDITORIAL WHERE NAME = 'Taurus'), 'La ciudad y los perros', 'Mario Vargas Llosa', 'Ficción', 408, TRUE, 1963),
((SELECT ID FROM EDITORIAL WHERE NAME = 'Taurus'), 'Conversación en La Catedral', 'Mario Vargas Llosa', 'Ficción política', 731, TRUE, 1969),
((SELECT ID FROM EDITORIAL WHERE NAME = 'Plataforma Editorial'), 'El laberinto de los espíritus', 'Carlos Ruiz Zafón', 'Misterio', 976, TRUE, 2016),
((SELECT ID FROM EDITORIAL WHERE NAME = 'Plataforma Editorial'), 'El prisionero del cielo', 'Carlos Ruiz Zafón', 'Misterio', 448, TRUE, 2011),
((SELECT ID FROM EDITORIAL WHERE NAME = 'Blackie Books'), 'Patria', 'Fernando Aramburu', 'Ficción contemporánea', 648, TRUE, 2016),
((SELECT ID FROM EDITORIAL WHERE NAME = 'Blackie Books'), 'Los vencejos', 'Fernando Aramburu', 'Ficción', 432, TRUE, 2021),
((SELECT ID FROM EDITORIAL WHERE NAME = 'Nórdica Libros'), 'El capitán Alatriste', 'Arturo Pérez-Reverte', 'Aventuras', 256, TRUE, 1996),
((SELECT ID FROM EDITORIAL WHERE NAME = 'Nórdica Libros'), 'La reina del sur', 'Arturo Pérez-Reverte', 'Thriller', 543, TRUE, 2002),
((SELECT ID FROM EDITORIAL WHERE NAME = 'Páginas de Espuma'), 'La verdad sobre el caso Savolta', 'Eduardo Mendoza', 'Misterio', 336, TRUE, 1975),
((SELECT ID FROM EDITORIAL WHERE NAME = 'Páginas de Espuma'), 'La ciudad de los prodigios', 'Eduardo Mendoza', 'Ficción histórica', 544, TRUE, 1986),
((SELECT ID FROM EDITORIAL WHERE NAME = 'Pre-Textos'), 'Nada', 'Carmen Laforet', 'Ficción', 288, TRUE, 1945),
((SELECT ID FROM EDITORIAL WHERE NAME = 'Pre-Textos'), 'La mujer nueva', 'Carmen Laforet', 'Ficción', 368, TRUE, 1955),
((SELECT ID FROM EDITORIAL WHERE NAME = 'Editorial Acantilado'), 'Crematorio', 'Rafael Chirbes', 'Ficción contemporánea', 448, TRUE, 2007),
((SELECT ID FROM EDITORIAL WHERE NAME = 'Editorial Acantilado'), 'En la orilla', 'Rafael Chirbes', 'Ficción', 432, TRUE, 2013),
((SELECT ID FROM EDITORIAL WHERE NAME = 'Impedimenta'), 'El cuaderno gris', 'Josep Pla', 'Memorias', 928, TRUE, 1966),
((SELECT ID FROM EDITORIAL WHERE NAME = 'Impedimenta'), 'Viaje en autobús', 'Josep Pla', 'Crónica', 288, TRUE, 1942),
((SELECT ID FROM EDITORIAL WHERE NAME = 'Sexto Piso'), 'Últimas tardes con Teresa', 'Juan Marsé', 'Ficción', 464, TRUE, 1966),
((SELECT ID FROM EDITORIAL WHERE NAME = 'Sexto Piso'), 'Si te dicen que caí', 'Juan Marsé', 'Ficción', 368, TRUE, 1973),
((SELECT ID FROM EDITORIAL WHERE NAME = 'Libros del Asteroide'), 'El hereje', 'Miguel Delibes', 'Ficción histórica', 576, TRUE, 1998),
((SELECT ID FROM EDITORIAL WHERE NAME = 'Libros del Asteroide'), 'Los santos inocentes', 'Miguel Delibes', 'Ficción rural', 224, TRUE, 1981),
((SELECT ID FROM EDITORIAL WHERE NAME = 'Galaxia Gutenberg'), 'La plaza del diamante', 'Mercè Rodoreda', 'Ficción', 232, TRUE, 1962),
((SELECT ID FROM EDITORIAL WHERE NAME = 'Galaxia Gutenberg'), 'Mirall trencat', 'Mercè Rodoreda', 'Ficción', 528, TRUE, 1974),
((SELECT ID FROM EDITORIAL WHERE NAME = 'Ediciones Siruela'), 'Cinco horas con Mario', 'Miguel Delibes', 'Ficción', 312, TRUE, 1966),
((SELECT ID FROM EDITORIAL WHERE NAME = 'Ediciones Siruela'), 'El camino', 'Miguel Delibes', 'Ficción', 208, TRUE, 1950),
((SELECT ID FROM EDITORIAL WHERE NAME = 'Minúscula'), 'La voz dormida', 'Dulce Chacón', 'Ficción histórica', 456, TRUE, 2002),
((SELECT ID FROM EDITORIAL WHERE NAME = 'Minúscula'), 'La viajera', 'Dulce Chacón', 'Ficción', 312, TRUE, 1995),
((SELECT ID FROM EDITORIAL WHERE NAME = 'Navona Editorial'), 'El lápiz del carpintero', 'Manuel Rivas', 'Ficción histórica', 248, TRUE, 1998),
((SELECT ID FROM EDITORIAL WHERE NAME = 'Navona Editorial'), '¿Qué me quieres, amor?', 'Manuel Rivas', 'Cuentos', 224, TRUE, 1995),
((SELECT ID FROM EDITORIAL WHERE NAME = 'Ediciones Obelisco'), 'Beatus Ille', 'Antonio Muñoz Molina', 'Ficción', 368, TRUE, 1986),
((SELECT ID FROM EDITORIAL WHERE NAME = 'Ediciones Obelisco'), 'Plenilunio', 'Antonio Muñoz Molina', 'Thriller', 464, TRUE, 1997),
((SELECT ID FROM EDITORIAL WHERE NAME = 'Editorial Almuzara'), 'El jinete polaco', 'Antonio Muñoz Molina', 'Ficción', 560, TRUE, 1991),
((SELECT ID FROM EDITORIAL WHERE NAME = 'Editorial Almuzara'), 'Sefarad', 'Antonio Muñoz Molina', 'Relatos', 544, TRUE, 2001),
((SELECT ID FROM EDITORIAL WHERE NAME = 'Ediciones Edhasa'), 'Enterrar a los muertos', 'Ignacio Martínez de Pisón', 'No ficción', 512, TRUE, 2005),
((SELECT ID FROM EDITORIAL WHERE NAME = 'Ediciones Edhasa'), 'El día de mañana', 'Ignacio Martínez de Pisón', 'Ficción', 464, TRUE, 2011),
((SELECT ID FROM EDITORIAL WHERE NAME = 'Errata Naturae'), 'Anatomía de un instante', 'Javier Cercas', 'No ficción', 456, TRUE, 2009),
((SELECT ID FROM EDITORIAL WHERE NAME = 'Errata Naturae'), 'Terra Alta', 'Javier Cercas', 'Thriller', 392, TRUE, 2019),
((SELECT ID FROM EDITORIAL WHERE NAME = 'Funambulista'), 'La ridícula idea de no volver a verte', 'Rosa Montero', 'Ensayo biográfico', 224, TRUE, 2013),
((SELECT ID FROM EDITORIAL WHERE NAME = 'Funambulista'), 'La carne', 'Rosa Montero', 'Ficción', 368, TRUE, 2016),
((SELECT ID FROM EDITORIAL WHERE NAME = 'Editorial Periférica'), 'El desorden de tu nombre', 'Juan José Millás', 'Ficción', 200, TRUE, 1988),
((SELECT ID FROM EDITORIAL WHERE NAME = 'Editorial Periférica'), 'La soledad era esto', 'Juan José Millás', 'Ficción', 224, TRUE, 1990),
((SELECT ID FROM EDITORIAL WHERE NAME = 'Caballo de Troya'), 'Corazón tan blanco', 'Javier Marías', 'Ficción', 336, TRUE, 1992),
((SELECT ID FROM EDITORIAL WHERE NAME = 'Caballo de Troya'), 'Todas las almas', 'Javier Marías', 'Ficción', 368, TRUE, 1989),
((SELECT ID FROM EDITORIAL WHERE NAME = 'Duomo Ediciones'), 'Mañana en la batalla piensa en mí', 'Javier Marías', 'Ficción', 464, TRUE, 1994),
((SELECT ID FROM EDITORIAL WHERE NAME = 'Duomo Ediciones'), 'Los enamoramientos', 'Javier Marías', 'Ficción', 416, TRUE, 2011),
((SELECT ID FROM EDITORIAL WHERE NAME = 'Punto de Lectura'), 'Juegos de la edad tardía', 'Luis Landero', 'Ficción', 352, TRUE, 1989),
((SELECT ID FROM EDITORIAL WHERE NAME = 'Punto de Lectura'), 'Caballeros de fortuna', 'Luis Landero', 'Ficción', 480, TRUE, 1994),
((SELECT ID FROM EDITORIAL WHERE NAME = 'Editorial Kalandraka'), 'El cuarto de atrás', 'Carmen Martín Gaite', 'Ficción', 208, TRUE, 1978),
((SELECT ID FROM EDITORIAL WHERE NAME = 'Editorial Kalandraka'), 'Nubosidad variable', 'Carmen Martín Gaite', 'Ficción', 304, TRUE, 1992),
((SELECT ID FROM EDITORIAL WHERE NAME = 'Ediciones Maeva'), 'La lluvia amarilla', 'Julio Llamazares', 'Ficción', 176, TRUE, 1988),
((SELECT ID FROM EDITORIAL WHERE NAME = 'Ediciones Maeva'), 'La noche de los tiempos', 'Antonio Muñoz Molina', 'Ficción', 736, TRUE, 2009),
((SELECT ID FROM EDITORIAL WHERE NAME = 'Editorial Bruño'), 'Dime quién soy', 'Julia Navarro', 'Ficción histórica', 1120, TRUE, 2010),
((SELECT ID FROM EDITORIAL WHERE NAME = 'Editorial Bruño'), 'Dispara, yo ya estoy muerto', 'Julia Navarro', 'Ficción histórica', 864, TRUE, 2013),
((SELECT ID FROM EDITORIAL WHERE NAME = 'Edelvives'), 'La lengua de las mariposas', 'Manuel Rivas', 'Cuentos', 160, TRUE, 1996),
((SELECT ID FROM EDITORIAL WHERE NAME = 'Edelvives'), 'El sur', 'Adelaida García Morales', 'Ficción', 96, TRUE, 1985),
((SELECT ID FROM EDITORIAL WHERE NAME = 'La Esfera de los Libros'), 'Inés y la alegría', 'Almudena Grandes', 'Ficción histórica', 672, TRUE, 2010),
((SELECT ID FROM EDITORIAL WHERE NAME = 'Penguin Random House'), 'El otoño del patriarca', 'Gabriel García Márquez', 'Ficción', 271, TRUE, 1975),
((SELECT ID FROM EDITORIAL WHERE NAME = 'Editorial Planeta'), 'El príncipe de la niebla', 'Carlos Ruiz Zafón', 'Fantasía juvenil', 224, TRUE, 1993),
((SELECT ID FROM EDITORIAL WHERE NAME = 'Anagrama'), 'El inquilino', 'Javier Cercas', 'Ficción', 208, TRUE, 1989),
((SELECT ID FROM EDITORIAL WHERE NAME = 'Alfaguara'), 'Eva Luna', 'Isabel Allende', 'Ficción', 288, TRUE, 1987),
((SELECT ID FROM EDITORIAL WHERE NAME = 'Tusquets Editores'), 'Bestiario', 'Julio Cortázar', 'Cuentos', 168, TRUE, 1951),
((SELECT ID FROM EDITORIAL WHERE NAME = 'Editorial Anaya'), 'Lazarillo de Tormes', 'Anónimo', 'Clásico', 128, TRUE, 1554),
((SELECT ID FROM EDITORIAL WHERE NAME = 'Ediciones SM'), 'El león, la bruja y el armario', 'C.S. Lewis', 'Fantasía', 208, TRUE, 1950),
((SELECT ID FROM EDITORIAL WHERE NAME = 'Editorial Santillana'), 'Inferno', 'Dan Brown', 'Thriller', 461, TRUE, 2013),
((SELECT ID FROM EDITORIAL WHERE NAME = 'Espasa'), 'Los pazos de Ulloa', 'Emilia Pardo Bazán', 'Clásico', 336, TRUE, 1886),
((SELECT ID FROM EDITORIAL WHERE NAME = 'Ediciones B'), 'Misión Olvido', 'María Dueñas', 'Ficción', 624, TRUE, 2012),
((SELECT ID FROM EDITORIAL WHERE NAME = 'RBA Libros'), 'La caída de los gigantes', 'Ken Follett', 'Ficción histórica', 1008, TRUE, 2010),
((SELECT ID FROM EDITORIAL WHERE NAME = 'Alianza Editorial'), 'La isla del día de antes', 'Umberto Eco', 'Ficción histórica', 528, TRUE, 1994),
((SELECT ID FROM EDITORIAL WHERE NAME = 'Seix Barral'), 'La mano de Fátima', 'Ildefonso Falcones', 'Ficción histórica', 736, TRUE, 2009),
((SELECT ID FROM EDITORIAL WHERE NAME = 'Debate'), 'Dragón Rojo', 'Thomas Harris', 'Thriller', 454, TRUE, 1981),
((SELECT ID FROM EDITORIAL WHERE NAME = 'Salamandra'), 'La identidad', 'Milan Kundera', 'Ficción', 168, TRUE, 1998),
((SELECT ID FROM EDITORIAL WHERE NAME = 'Ediciones Destino'), 'Homenaje a Cataluña', 'George Orwell', 'No ficción', 248, TRUE, 1938),
((SELECT ID FROM EDITORIAL WHERE NAME = 'Grijalbo'), 'Nueve cuentos', 'J.D. Salinger', 'Cuentos', 198, TRUE, 1953),
((SELECT ID FROM EDITORIAL WHERE NAME = 'Círculo de Lectores'), 'Del amor y otros demonios', 'Gabriel García Márquez', 'Ficción', 147, TRUE, 1994),
((SELECT ID FROM EDITORIAL WHERE NAME = 'Ediciones Cátedra'), 'Mazurca para dos muertos', 'Camilo José Cela', 'Ficción', 304, TRUE, 1983),
((SELECT ID FROM EDITORIAL WHERE NAME = 'Editorial Crítica'), 'Informe sobre ciegos', 'Ernesto Sabato', 'Ficción', 256, TRUE, 1961),
((SELECT ID FROM EDITORIAL WHERE NAME = 'Paidós'), 'El gallo de oro', 'Juan Rulfo', 'Relato', 96, TRUE, 1980),
((SELECT ID FROM EDITORIAL WHERE NAME = 'Ariel'), 'El libro de arena', 'Jorge Luis Borges', 'Cuentos', 176, TRUE, 1975),
((SELECT ID FROM EDITORIAL WHERE NAME = 'Taurus'), 'La tía Julia y el escribidor', 'Mario Vargas Llosa', 'Ficción', 448, TRUE, 1977),
((SELECT ID FROM EDITORIAL WHERE NAME = 'Plataforma Editorial'), 'El palacio de la medianoche', 'Carlos Ruiz Zafón', 'Fantasía juvenil', 288, TRUE, 1994),
((SELECT ID FROM EDITORIAL WHERE NAME = 'Blackie Books'), 'Años lentos', 'Fernando Aramburu', 'Ficción', 336, TRUE, 2012),
((SELECT ID FROM EDITORIAL WHERE NAME = 'Nórdica Libros'), 'El Club Dumas', 'Arturo Pérez-Reverte', 'Misterio', 384, TRUE, 1993),
((SELECT ID FROM EDITORIAL WHERE NAME = 'Páginas de Espuma'), 'Sin noticias de Gurb', 'Eduardo Mendoza', 'Comedia', 144, TRUE, 1991),
((SELECT ID FROM EDITORIAL WHERE NAME = 'Pre-Textos'), 'La isla y los demonios', 'Carmen Laforet', 'Ficción', 304, TRUE, 1952),
((SELECT ID FROM EDITORIAL WHERE NAME = 'Editorial Acantilado'), 'La larga marcha', 'Rafael Chirbes', 'Ficción', 520, TRUE, 1996),
((SELECT ID FROM EDITORIAL WHERE NAME = 'Impedimenta'), 'El pasajero', 'Josep Pla', 'Narrativa', 256, TRUE, 1925),
((SELECT ID FROM EDITORIAL WHERE NAME = 'Sexto Piso'), 'El embrujo de Shanghai', 'Juan Marsé', 'Ficción', 416, TRUE, 1993),
((SELECT ID FROM EDITORIAL WHERE NAME = 'Libros del Asteroide'), 'Señora de rojo sobre fondo gris', 'Miguel Delibes', 'Ficción', 176, TRUE, 1991),
((SELECT ID FROM EDITORIAL WHERE NAME = 'Galaxia Gutenberg'), 'La calle de las camelias', 'Mercè Rodoreda', 'Ficción', 256, TRUE, 1966),
((SELECT ID FROM EDITORIAL WHERE NAME = 'Ediciones Siruela'), 'Las ratas', 'Miguel Delibes', 'Ficción rural', 192, TRUE, 1962),
((SELECT ID FROM EDITORIAL WHERE NAME = 'Minúscula'), 'Algún amor que no mate', 'Dulce Chacón', 'Poesía', 96, TRUE, 1996),
((SELECT ID FROM EDITORIAL WHERE NAME = 'Navona Editorial'), 'Los libros arden mal', 'Manuel Rivas', 'Ficción', 656, TRUE, 2006),
((SELECT ID FROM EDITORIAL WHERE NAME = 'Ediciones Obelisco'), 'El invierno en Lisboa', 'Antonio Muñoz Molina', 'Ficción', 256, TRUE, 1987),
((SELECT ID FROM EDITORIAL WHERE NAME = 'Editorial Almuzara'), 'Sepharad', 'Antonio Muñoz Molina', 'Relatos', 544, TRUE, 2001),
((SELECT ID FROM EDITORIAL WHERE NAME = 'Ediciones Edhasa'), 'Carreteras secundarias', 'Ignacio Martínez de Pisón', 'Ficción', 256, TRUE, 1996),
((SELECT ID FROM EDITORIAL WHERE NAME = 'Errata Naturae'), 'El vientre de la ballena', 'Javier Cercas', 'Ficción', 144, TRUE, 1997),
((SELECT ID FROM EDITORIAL WHERE NAME = 'Funambulista'), 'Lágrimas en la lluvia', 'Rosa Montero', 'Ciencia ficción', 416, TRUE, 2011),
((SELECT ID FROM EDITORIAL WHERE NAME = 'Editorial Periférica'), 'Papel mojado', 'Juan José Millás', 'Ficción', 272, TRUE, 1983),
((SELECT ID FROM EDITORIAL WHERE NAME = 'Caballo de Troya'), 'Tu rostro mañana', 'Javier Marías', 'Ficción', 1504, TRUE, 2002),
((SELECT ID FROM EDITORIAL WHERE NAME = 'Duomo Ediciones'), 'Negra espalda del tiempo', 'Javier Marías', 'Ensayo', 400, TRUE, 1998),
((SELECT ID FROM EDITORIAL WHERE NAME = 'Punto de Lectura'), 'Hoy, Júpiter', 'Luis Landero', 'Ficción', 272, TRUE, 2007),
((SELECT ID FROM EDITORIAL WHERE NAME = 'Editorial Kalandraka'), 'Caperucita en Manhattan', 'Carmen Martín Gaite', 'Infantil', 208, TRUE, 1990),
((SELECT ID FROM EDITORIAL WHERE NAME = 'Ediciones Maeva'), 'Luna de lobos', 'Julio Llamazares', 'Ficción', 192, TRUE, 1985),
((SELECT ID FROM EDITORIAL WHERE NAME = 'Editorial Bruño'), 'Hermanos de sangre', 'Julia Navarro', 'Ficción histórica', 928, TRUE, 2015),
((SELECT ID FROM EDITORIAL WHERE NAME = 'Edelvives'), 'El silencio roto', 'Montserrat del Amo', 'Ficción', 288, TRUE, 1997),
((SELECT ID FROM EDITORIAL WHERE NAME = 'La Esfera de los Libros'), 'El corazón helado', 'Almudena Grandes', 'Ficción', 1104, TRUE, 2007),
((SELECT ID FROM EDITORIAL WHERE NAME = 'Penguin Random House'), 'Noticia de un secuestro', 'Gabriel García Márquez', 'No ficción', 315, TRUE, 1996),
((SELECT ID FROM EDITORIAL WHERE NAME = 'Editorial Planeta'), 'Las luces de septiembre', 'Carlos Ruiz Zafón', 'Fantasía juvenil', 256, TRUE, 1995),
((SELECT ID FROM EDITORIAL WHERE NAME = 'Anagrama'), 'Outlaws', 'Javier Cercas', 'Ficción', 224, TRUE, 2022),
((SELECT ID FROM EDITORIAL WHERE NAME = 'Alfaguara'), 'De amor y de sombra', 'Isabel Allende', 'Ficción', 271, TRUE, 1984),
((SELECT ID FROM EDITORIAL WHERE NAME = 'Tusquets Editores'), 'Final del juego', 'Julio Cortázar', 'Cuentos', 232, TRUE, 1956),
((SELECT ID FROM EDITORIAL WHERE NAME = 'Editorial Anaya'), 'La vida del Buscón', 'Francisco de Quevedo', 'Clásico', 256, TRUE, 1626),
((SELECT ID FROM EDITORIAL WHERE NAME = 'Ediciones SM'), 'Matilda', 'Roald Dahl', 'Infantil', 240, TRUE, 1988),
((SELECT ID FROM EDITORIAL WHERE NAME = 'Editorial Santillana'), 'El símbolo perdido', 'Dan Brown', 'Thriller', 509, TRUE, 2009),
((SELECT ID FROM EDITORIAL WHERE NAME = 'Espasa'), 'La madre naturaleza', 'Emilia Pardo Bazán', 'Clásico', 456, TRUE, 1887),
((SELECT ID FROM EDITORIAL WHERE NAME = 'Ediciones B'), 'Las hijas del Capitán', 'María Dueñas', 'Ficción histórica', 784, TRUE, 2018),
((SELECT ID FROM EDITORIAL WHERE NAME = 'RBA Libros'), 'El invierno del mundo', 'Ken Follett', 'Ficción histórica', 1024, TRUE, 2012),
((SELECT ID FROM EDITORIAL WHERE NAME = 'Alianza Editorial'), 'Baudolino', 'Umberto Eco', 'Ficción histórica', 568, TRUE, 2000),
((SELECT ID FROM EDITORIAL WHERE NAME = 'Seix Barral'), 'El pintor de almas', 'Ildefonso Falcones', 'Ficción histórica', 688, TRUE, 2019),
((SELECT ID FROM EDITORIAL WHERE NAME = 'Debate'), 'Cari Mora', 'Thomas Harris', 'Thriller', 304, TRUE, 2019),
((SELECT ID FROM EDITORIAL WHERE NAME = 'Salamandra'), 'La inmortalidad', 'Milan Kundera', 'Ficción filosófica', 384, TRUE, 1990),
((SELECT ID FROM EDITORIAL WHERE NAME = 'Ediciones Destino'), 'El camino de Wigan Pier', 'George Orwell', 'No ficción', 264, TRUE, 1937),
((SELECT ID FROM EDITORIAL WHERE NAME = 'Grijalbo'), 'Levantad, carpinteros, la viga del tejado', 'J.D. Salinger', 'Ficción', 256, TRUE, 1963),
((SELECT ID FROM EDITORIAL WHERE NAME = 'Círculo de Lectores'), 'La mala hora', 'Gabriel García Márquez', 'Ficción', 183, TRUE, 1962),
((SELECT ID FROM EDITORIAL WHERE NAME = 'Ediciones Cátedra'), 'Cristo versus Arizona', 'Camilo José Cela', 'Ficción', 192, TRUE, 1988),
((SELECT ID FROM EDITORIAL WHERE NAME = 'Editorial Crítica'), 'Abbadón el exterminador', 'Ernesto Sabato', 'Ficción', 543, TRUE, 1974),
((SELECT ID FROM EDITORIAL WHERE NAME = 'Paidós'), 'Carta a una señorita en París', 'Julio Cortázar', 'Cuento', 24, TRUE, 1951),
((SELECT ID FROM EDITORIAL WHERE NAME = 'Ariel'), 'Historia universal de la infamia', 'Jorge Luis Borges', 'Cuentos', 168, TRUE, 1935),
((SELECT ID FROM EDITORIAL WHERE NAME = 'Taurus'), 'Pantaleón y las visitadoras', 'Mario Vargas Llosa', 'Ficción', 320, TRUE, 1973),
((SELECT ID FROM EDITORIAL WHERE NAME = 'Plataforma Editorial'), 'Marina', 'Carlos Ruiz Zafón', 'Misterio juvenil', 312, TRUE, 1999),
((SELECT ID FROM EDITORIAL WHERE NAME = 'Blackie Books'), 'Fuegos con limón', 'Fernando Aramburu', 'Cuentos', 224, TRUE, 1996),
((SELECT ID FROM EDITORIAL WHERE NAME = 'Nórdica Libros'), 'La tabla de Flandes', 'Arturo Pérez-Reverte', 'Misterio', 384, TRUE, 1990),
((SELECT ID FROM EDITORIAL WHERE NAME = 'Páginas de Espuma'), 'El misterio de la cripta embrujada', 'Eduardo Mendoza', 'Misterio', 224, TRUE, 1979),
((SELECT ID FROM EDITORIAL WHERE NAME = 'Pre-Textos'), 'Al volver la esquina', 'Carmen Laforet', 'Ficción', 448, TRUE, 2004),
((SELECT ID FROM EDITORIAL WHERE NAME = 'Editorial Acantilado'), 'Mimoun', 'Rafael Chirbes', 'Ficción', 272, TRUE, 1988),
((SELECT ID FROM EDITORIAL WHERE NAME = 'Impedimenta'), 'Notes disperses', 'Josep Pla', 'Ensayo', 384, TRUE, 1969),
((SELECT ID FROM EDITORIAL WHERE NAME = 'Sexto Piso'), 'Rabos de lagartija', 'Juan Marsé', 'Ficción', 368, TRUE, 2000),
((SELECT ID FROM EDITORIAL WHERE NAME = 'Libros del Asteroide'), 'Diario de un jubilado', 'Miguel Delibes', 'No ficción', 272, TRUE, 1995),
((SELECT ID FROM EDITORIAL WHERE NAME = 'Galaxia Gutenberg'), 'Jardín umbría', 'Mercè Rodoreda', 'Ficción', 240, TRUE, 1989),
((SELECT ID FROM EDITORIAL WHERE NAME = 'Ediciones Siruela'), 'Parábola del náufrago', 'Miguel Delibes', 'Ficción', 208, TRUE, 1969),
((SELECT ID FROM EDITORIAL WHERE NAME = 'Minúscula'), 'Contra el desprestigio de la altura', 'Dulce Chacón', 'Poesía', 80, TRUE, 1995),
((SELECT ID FROM EDITORIAL WHERE NAME = 'Navona Editorial'), 'En salvaje compañía', 'Manuel Rivas', 'Ficción', 288, TRUE, 1994),
((SELECT ID FROM EDITORIAL WHERE NAME = 'Ediciones Obelisco'), 'Beltenebros', 'Antonio Muñoz Molina', 'Thriller', 208, TRUE, 1989),
((SELECT ID FROM EDITORIAL WHERE NAME = 'Editorial Almuzara'), 'Carlota Fainberg', 'Antonio Muñoz Molina', 'Ficción', 256, TRUE, 1999),
((SELECT ID FROM EDITORIAL WHERE NAME = 'Ediciones Edhasa'), 'El tiempo de las mujeres', 'Ignacio Martínez de Pisón', 'Ficción', 288, TRUE, 2003),
((SELECT ID FROM EDITORIAL WHERE NAME = 'Errata Naturae'), 'Las leyes de la frontera', 'Javier Cercas', 'Ficción', 384, TRUE, 2012),
((SELECT ID FROM EDITORIAL WHERE NAME = 'Funambulista'), 'El peso del corazón', 'Rosa Montero', 'Ciencia ficción', 448, TRUE, 2015),
((SELECT ID FROM EDITORIAL WHERE NAME = 'Editorial Periférica'), 'Dos mujeres en Praga', 'Juan José Millás', 'Ficción', 272, TRUE, 2002),
((SELECT ID FROM EDITORIAL WHERE NAME = 'Caballo de Troya'), 'Una comedia ligera', 'Eduardo Mendoza', 'Ficción', 496, TRUE, 1996),
((SELECT ID FROM EDITORIAL WHERE NAME = 'Duomo Ediciones'), 'Cuando los tontos manden', 'Javier Marías', 'Ensayo', 336, TRUE, 2013),
((SELECT ID FROM EDITORIAL WHERE NAME = 'Punto de Lectura'), 'Entre líneas: el cuento o la vida', 'Luis Landero', 'Ensayo', 272, TRUE, 2001),
((SELECT ID FROM EDITORIAL WHERE NAME = 'Editorial Kalandraka'), 'Irse de casa', 'Carmen Martín Gaite', 'Ficción', 304, TRUE, 1998),
((SELECT ID FROM EDITORIAL WHERE NAME = 'Ediciones Maeva'), 'Distintas formas de mirar el agua', 'Julio Llamazares', 'Relatos', 176, TRUE, 2015),
((SELECT ID FROM EDITORIAL WHERE NAME = 'Editorial Bruño'), 'De ninguna parte', 'Julia Navarro', 'Ficción', 768, TRUE, 2024),
((SELECT ID FROM EDITORIAL WHERE NAME = 'Edelvives'), 'Todo lo que era sólido', 'Antonio Muñoz Molina', 'Ensayo', 240, TRUE, 2013),
((SELECT ID FROM EDITORIAL WHERE NAME = 'La Esfera de los Libros'), 'Los besos en el pan', 'Almudena Grandes', 'Cuentos', 368, TRUE, 2015),
((SELECT ID FROM EDITORIAL WHERE NAME = 'Penguin Random House'), 'Vivir para contarla', 'Gabriel García Márquez', 'Autobiografía', 569, TRUE, 2002),
((SELECT ID FROM EDITORIAL WHERE NAME = 'Editorial Planeta'), 'El palacio de la medianoche', 'Carlos Ruiz Zafón', 'Fantasía', 288, TRUE, 1994),
((SELECT ID FROM EDITORIAL WHERE NAME = 'Anagrama'), 'La velocidad de la luz', 'Javier Cercas', 'Ficción', 432, TRUE, 2005),
((SELECT ID FROM EDITORIAL WHERE NAME = 'Alfaguara'), 'El plan infinito', 'Isabel Allende', 'Ficción', 448, TRUE, 1991),
((SELECT ID FROM EDITORIAL WHERE NAME = 'Tusquets Editores'), 'Historias de cronopios y de famas', 'Julio Cortázar', 'Cuentos', 152, TRUE, 1962),
((SELECT ID FROM EDITORIAL WHERE NAME = 'Editorial Anaya'), 'Rinconete y Cortadillo', 'Miguel de Cervantes', 'Clásico', 96, TRUE, 1613),
((SELECT ID FROM EDITORIAL WHERE NAME = 'Ediciones SM'), 'Charlie y la fábrica de chocolate', 'Roald Dahl', 'Infantil', 176, TRUE, 1964),
((SELECT ID FROM EDITORIAL WHERE NAME = 'Editorial Santillana'), 'Origen', 'Dan Brown', 'Thriller', 461, TRUE, 2017),
((SELECT ID FROM EDITORIAL WHERE NAME = 'Espasa'), 'La tribuna', 'Emilia Pardo Bazán', 'Realismo', 272, TRUE, 1883),
((SELECT ID FROM EDITORIAL WHERE NAME = 'Ediciones B'), 'Sira', 'María Dueñas', 'Ficción histórica', 800, TRUE, 2021),
((SELECT ID FROM EDITORIAL WHERE NAME = 'RBA Libros'), 'El umbral de la eternidad', 'Ken Follett', 'Ficción histórica', 1152, TRUE, 2014),
((SELECT ID FROM EDITORIAL WHERE NAME = 'Alianza Editorial'), 'Número cero', 'Umberto Eco', 'Ficción', 224, TRUE, 2015),
((SELECT ID FROM EDITORIAL WHERE NAME = 'Seix Barral'), 'Una historia española', 'Ildefonso Falcones', 'Ficción histórica', 800, TRUE, 2022),
((SELECT ID FROM EDITORIAL WHERE NAME = 'Debate'), 'El silencio de los corderos 2', 'Thomas Harris', 'Thriller', 368, TRUE, 2006),
((SELECT ID FROM EDITORIAL WHERE NAME = 'Salamandra'), 'La lentitud', 'Milan Kundera', 'Ficción', 160, TRUE, 1995),
((SELECT ID FROM EDITORIAL WHERE NAME = 'Ediciones Destino'), 'Los días de Birmania', 'George Orwell', 'Ficción', 312, TRUE, 1934),
((SELECT ID FROM EDITORIAL WHERE NAME = 'Grijalbo'), 'Seymour: una introducción', 'J.D. Salinger', 'Ficción', 96, TRUE, 1963),
((SELECT ID FROM EDITORIAL WHERE NAME = 'Círculo de Lectores'), 'Ojos de perro azul', 'Gabriel García Márquez', 'Cuentos', 152, TRUE, 1947),
((SELECT ID FROM EDITORIAL WHERE NAME = 'Ediciones Cátedra'), 'El asesinato del perdedor', 'Camilo José Cela', 'Ficción', 288, TRUE, 1994),
((SELECT ID FROM EDITORIAL WHERE NAME = 'Editorial Crítica'), 'Antes del fin', 'Ernesto Sabato', 'Ensayo', 224, TRUE, 1998),
((SELECT ID FROM EDITORIAL WHERE NAME = 'Paidós'), 'Axolotl', 'Julio Cortázar', 'Cuento', 16, TRUE, 1956),
((SELECT ID FROM EDITORIAL WHERE NAME = 'Ariel'), 'El hacedor', 'Jorge Luis Borges', 'Poesía y prosa', 168, TRUE, 1960),
((SELECT ID FROM EDITORIAL WHERE NAME = 'Taurus'), 'El sueño del celta', 'Mario Vargas Llosa', 'Ficción histórica', 456, TRUE, 2010),
((SELECT ID FROM EDITORIAL WHERE NAME = 'Plataforma Editorial'), 'El príncipe de la niebla', 'Carlos Ruiz Zafón', 'Juvenil', 224, TRUE, 1993),
((SELECT ID FROM EDITORIAL WHERE NAME = 'Blackie Books'), 'El vigilante del fiordo', 'Fernando Aramburu', 'Relatos', 320, TRUE, 2016),
((SELECT ID FROM EDITORIAL WHERE NAME = 'Nórdica Libros'), 'Territorio Comanche', 'Arturo Pérez-Reverte', 'Ficción bélica', 208, TRUE, 1994),
((SELECT ID FROM EDITORIAL WHERE NAME = 'Páginas de Espuma'), 'El año del diluvio', 'Eduardo Mendoza', 'Ficción', 336, TRUE, 1992),
((SELECT ID FROM EDITORIAL WHERE NAME = 'Pre-Textos'), 'Mis páginas mejores', 'Carmen Laforet', 'Antología', 288, TRUE, 1956),
((SELECT ID FROM EDITORIAL WHERE NAME = 'Editorial Acantilado'), 'Paris-Austerlitz', 'Rafael Chirbes', 'Ficción', 368, TRUE, 2016),
((SELECT ID FROM EDITORIAL WHERE NAME = 'Impedimenta'), 'Un señor de Barcelona', 'Josep Pla', 'Narrativa', 304, TRUE, 1951),
((SELECT ID FROM EDITORIAL WHERE NAME = 'Sexto Piso'), 'La muchacha de las bragas de oro', 'Juan Marsé', 'Ficción', 304, TRUE, 1978),
((SELECT ID FROM EDITORIAL WHERE NAME = 'Libros del Asteroide'), 'Diario de un cazador', 'Miguel Delibes', 'Ficción', 288, TRUE, 1955),
((SELECT ID FROM EDITORIAL WHERE NAME = 'Galaxia Gutenberg'), 'Viajes y flores', 'Mercè Rodoreda', 'Relatos', 192, TRUE, 1980),
((SELECT ID FROM EDITORIAL WHERE NAME = 'Ediciones Siruela'), 'Mi idolatrado hijo Sisí', 'Miguel Delibes', 'Ficción', 240, TRUE, 1953),
((SELECT ID FROM EDITORIAL WHERE NAME = 'Minúscula'), 'Querrán ponerle nombre', 'Dulce Chacón', 'Poesía', 88, TRUE, 1992),
((SELECT ID FROM EDITORIAL WHERE NAME = 'Navona Editorial'), 'Todo es silencio', 'Manuel Rivas', 'Thriller', 304, TRUE, 2010),
((SELECT ID FROM EDITORIAL WHERE NAME = 'Ediciones Obelisco'), 'Un Robinson urbano', 'Antonio Muñoz Molina', 'Ensayo', 256, TRUE, 1993),
((SELECT ID FROM EDITORIAL WHERE NAME = 'Editorial Almuzara'), 'Ardor guerrero', 'Antonio Muñoz Molina', 'Ficción', 256, TRUE, 1995),
((SELECT ID FROM EDITORIAL WHERE NAME = 'Ediciones Edhasa'), 'El fin de los buenos tiempos', 'Ignacio Martínez de Pisón', 'Ficción', 352, TRUE, 1994),
((SELECT ID FROM EDITORIAL WHERE NAME = 'Errata Naturae'), 'Independencia', 'Javier Cercas', 'Ficción', 384, TRUE, 2021),
((SELECT ID FROM EDITORIAL WHERE NAME = 'Funambulista'), 'Historia del Rey Transparente', 'Rosa Montero', 'Ficción histórica', 400, TRUE, 2005),
((SELECT ID FROM EDITORIAL WHERE NAME = 'Editorial Periférica'), 'El mundo', 'Juan José Millás', 'Ficción', 240, TRUE, 2007),
((SELECT ID FROM EDITORIAL WHERE NAME = 'Caballo de Troya'), 'Berta Isla', 'Javier Marías', 'Ficción', 528, TRUE, 2017),
((SELECT ID FROM EDITORIAL WHERE NAME = 'Duomo Ediciones'), 'Salvajes y sentimentales', 'Javier Marías', 'Ensayo', 272, TRUE, 2000),
((SELECT ID FROM EDITORIAL WHERE NAME = 'Punto de Lectura'), 'El guitarrista', 'Luis Landero', 'Ficción', 336, TRUE, 2002),
((SELECT ID FROM EDITORIAL WHERE NAME = 'Editorial Kalandraka'), 'Lo raro es vivir', 'Carmen Martín Gaite', 'Ensayo', 336, TRUE, 1996),
((SELECT ID FROM EDITORIAL WHERE NAME = 'Ediciones Maeva'), 'Escenas de cine mudo', 'Julio Llamazares', 'Ficción', 208, TRUE, 1994),
((SELECT ID FROM EDITORIAL WHERE NAME = 'Editorial Bruño'), 'Tú no matarás', 'Julia Navarro', 'Thriller', 960, TRUE, 2018),
((SELECT ID FROM EDITORIAL WHERE NAME = 'Edelvives'), 'La tierra convulsa', 'Manuel Rivas', 'Narrativa', 304, TRUE, 2017),
((SELECT ID FROM EDITORIAL WHERE NAME = 'La Esfera de los Libros'), 'Atlas de geografía humana', 'Almudena Grandes', 'Ficción', 464, TRUE, 1998),
((SELECT ID FROM EDITORIAL WHERE NAME = 'Penguin Random House'), '12 cuentos peregrinos', 'Gabriel García Márquez', 'Cuentos', 224, TRUE, 1992),
((SELECT ID FROM EDITORIAL WHERE NAME = 'Editorial Planeta'), 'La niebla', 'Carlos Ruiz Zafón', 'Novela corta', 160, TRUE, 1993),
((SELECT ID FROM EDITORIAL WHERE NAME = 'Anagrama'), 'El móvil', 'Javier Cercas', 'Ficción', 96, TRUE, 1987),
((SELECT ID FROM EDITORIAL WHERE NAME = 'Alfaguara'), 'Hija de la fortuna', 'Isabel Allende', 'Ficción histórica', 399, TRUE, 1999),
((SELECT ID FROM EDITORIAL WHERE NAME = 'Tusquets Editores'), 'Octaedro', 'Julio Cortázar', 'Cuentos', 168, TRUE, 1974),
((SELECT ID FROM EDITORIAL WHERE NAME = 'Editorial Anaya'), 'El coloquio de los perros', 'Miguel de Cervantes', 'Clásico', 112, TRUE, 1613),
((SELECT ID FROM EDITORIAL WHERE NAME = 'Ediciones SM'), 'James y el melocotón gigante', 'Roald Dahl', 'Infantil', 176, TRUE, 1961),
((SELECT ID FROM EDITORIAL WHERE NAME = 'Editorial Santillana'), 'Fortaleza digital', 'Dan Brown', 'Thriller', 448, TRUE, 1998),
((SELECT ID FROM EDITORIAL WHERE NAME = 'Espasa'), 'Un viaje de novios', 'Emilia Pardo Bazán', 'Ficción', 288, TRUE, 1881),
((SELECT ID FROM EDITORIAL WHERE NAME = 'Ediciones B'), 'La Reina descalza', 'María Dueñas', 'Ficción histórica', 656, TRUE, 2013),
((SELECT ID FROM EDITORIAL WHERE NAME = 'RBA Libros'), 'Noche sobre las aguas', 'Ken Follett', 'Thriller', 464, TRUE, 1991),
((SELECT ID FROM EDITORIAL WHERE NAME = 'Alianza Editorial'), 'El cementerio de Praga', 'Umberto Eco', 'Ficción histórica', 560, TRUE, 2010),
((SELECT ID FROM EDITORIAL WHERE NAME = 'Seix Barral'), 'La luz de la noche', 'Ildefonso Falcones', 'Ficción histórica', 672, TRUE, 2023),
((SELECT ID FROM EDITORIAL WHERE NAME = 'Debate'), 'Black Sunday', 'Thomas Harris', 'Thriller', 318, TRUE, 1975),
((SELECT ID FROM EDITORIAL WHERE NAME = 'Salamandra'), 'El libro de la risa y el olvido', 'Milan Kundera', 'Ficción', 288, TRUE, 1979),
((SELECT ID FROM EDITORIAL WHERE NAME = 'Ediciones Destino'), 'La hija del clérigo', 'George Orwell', 'Ficción', 320, TRUE, 1935),
((SELECT ID FROM EDITORIAL WHERE NAME = 'Grijalbo'), 'Hapworth 16, 1924', 'J.D. Salinger', 'Ficción epistolar', 128, TRUE, 1965),
((SELECT ID FROM EDITORIAL WHERE NAME = 'Círculo de Lectores'), 'La hojarasca', 'Gabriel García Márquez', 'Ficción', 145, TRUE, 1955),
((SELECT ID FROM EDITORIAL WHERE NAME = 'Ediciones Cátedra'), 'Oficio de tinieblas 5', 'Camilo José Cela', 'Ficción', 224, TRUE, 1973),
((SELECT ID FROM EDITORIAL WHERE NAME = 'Editorial Crítica'), 'Hombres y engranajes', 'Ernesto Sabato', 'Ensayo', 192, TRUE, 1951),
((SELECT ID FROM EDITORIAL WHERE NAME = 'Paidós'), 'La noche boca arriba', 'Julio Cortázar', 'Cuento', 12, TRUE, 1956),
((SELECT ID FROM EDITORIAL WHERE NAME = 'Ariel'), 'Los conjurados', 'Jorge Luis Borges', 'Poesía', 96, TRUE, 1985),
((SELECT ID FROM EDITORIAL WHERE NAME = 'Taurus'), 'La fiesta del Chivo', 'Mario Vargas Llosa', 'Ficción histórica', 517, TRUE, 2000),
((SELECT ID FROM EDITORIAL WHERE NAME = 'Plataforma Editorial'), 'Rosa de fuego', 'Carlos Ruiz Zafón', 'Misterio', 144, TRUE, 2012),
((SELECT ID FROM EDITORIAL WHERE NAME = 'Blackie Books'), 'Autorretrato sin mí', 'Fernando Aramburu', 'Ensayo', 288, TRUE, 2018),
((SELECT ID FROM EDITORIAL WHERE NAME = 'Nórdica Libros'), 'Limpieza de sangre', 'Arturo Pérez-Reverte', 'Aventuras', 304, TRUE, 1997),
((SELECT ID FROM EDITORIAL WHERE NAME = 'Páginas de Espuma'), 'Mauricio o las elecciones primarias', 'Eduardo Mendoza', 'Comedia', 224, TRUE, 2006),
((SELECT ID FROM EDITORIAL WHERE NAME = 'Pre-Textos'), 'La llamada', 'Carmen Laforet', 'Ficción', 368, TRUE, 1954),
((SELECT ID FROM EDITORIAL WHERE NAME = 'Editorial Acantilado'), 'Los viejos amigos', 'Rafael Chirbes', 'Ficción', 256, TRUE, 2003),
((SELECT ID FROM EDITORIAL WHERE NAME = 'Impedimenta'), 'Homenots', 'Josep Pla', 'Biografías', 416, TRUE, 1969),
((SELECT ID FROM EDITORIAL WHERE NAME = 'Sexto Piso'), 'Un día volveré', 'Juan Marsé', 'Ficción', 336, TRUE, 1982),
((SELECT ID FROM EDITORIAL WHERE NAME = 'Libros del Asteroide'), 'La mortaja', 'Miguel Delibes', 'Ficción', 208, TRUE, 1970),
((SELECT ID FROM EDITORIAL WHERE NAME = 'Galaxia Gutenberg'), 'Semblanza de Barcelona', 'Mercè Rodoreda', 'Ensayo', 128, TRUE, 1967),
((SELECT ID FROM EDITORIAL WHERE NAME = 'Ediciones Siruela'), 'Vivir al día', 'Miguel Delibes', 'Ensayo', 336, TRUE, 1985),
((SELECT ID FROM EDITORIAL WHERE NAME = 'Minúscula'), 'Las palabras de la piedra', 'Dulce Chacón', 'Poesía', 104, TRUE, 1993),
((SELECT ID FROM EDITORIAL WHERE NAME = 'Navona Editorial'), 'La mano del emigrante', 'Manuel Rivas', 'Ficción', 240, TRUE, 2000),
((SELECT ID FROM EDITORIAL WHERE NAME = 'Ediciones Obelisco'), 'Ventanas de Manhattan', 'Antonio Muñoz Molina', 'Ensayo', 288, TRUE, 2004),
((SELECT ID FROM EDITORIAL WHERE NAME = 'Editorial Almuzara'), 'La disciplina de la vanidad', 'Antonio Muñoz Molina', 'Ensayo', 304, TRUE, 1996),
((SELECT ID FROM EDITORIAL WHERE NAME = 'Ediciones Edhasa'), 'Alguien te observa', 'Ignacio Martínez de Pisón', 'Thriller', 336, TRUE, 2007),
((SELECT ID FROM EDITORIAL WHERE NAME = 'Errata Naturae'), 'El castillo de Barbazul', 'Javier Cercas', 'Ensayo', 192, TRUE, 2007),
((SELECT ID FROM EDITORIAL WHERE NAME = 'Funambulista'), 'Instrucciones para salvar el mundo', 'Rosa Montero', 'Ficción', 352, TRUE, 2008),
((SELECT ID FROM EDITORIAL WHERE NAME = 'Editorial Periférica'), 'El orden alfabético', 'Juan José Millás', 'Ficción', 224, TRUE, 1998),
((SELECT ID FROM EDITORIAL WHERE NAME = 'Caballo de Troya'), 'Tomás Nevinson', 'Javier Marías', 'Ficción', 624, TRUE, 2021),
((SELECT ID FROM EDITORIAL WHERE NAME = 'Duomo Ediciones'), 'Pasiones pasadas', 'Javier Marías', 'Ensayo', 448, TRUE, 1991),
((SELECT ID FROM EDITORIAL WHERE NAME = 'Punto de Lectura'), 'La vida negociable', 'Luis Landero', 'Ficción', 368, TRUE, 2017),
((SELECT ID FROM EDITORIAL WHERE NAME = 'Editorial Kalandraka'), 'La búsqueda de interlocutor', 'Carmen Martín Gaite', 'Ensayo', 256, TRUE, 1973),
((SELECT ID FROM EDITORIAL WHERE NAME = 'Ediciones Maeva'), 'El cielo de Madrid', 'Julio Llamazares', 'Narrativa', 192, TRUE, 2005),
((SELECT ID FROM EDITORIAL WHERE NAME = 'Editorial Bruño'), 'Historia de un canalla', 'Julia Navarro', 'Ficción', 832, TRUE, 2016),
((SELECT ID FROM EDITORIAL WHERE NAME = 'Edelvives'), 'El periodismo es un cuento', 'Manuel Rivas', 'Ensayo', 280, TRUE, 1997),
((SELECT ID FROM EDITORIAL WHERE NAME = 'La Esfera de los Libros'), 'Castillos de cartón', 'Almudena Grandes', 'Ficción', 624, TRUE, 2004),
((SELECT ID FROM EDITORIAL WHERE NAME = 'Penguin Random House'), 'Relato de un náufrago', 'Gabriel García Márquez', 'No ficción', 127, TRUE, 1970),
((SELECT ID FROM EDITORIAL WHERE NAME = 'Editorial Planeta'), 'El vuelo del ángel', 'Carlos Ruiz Zafón', 'Novela gráfica', 256, TRUE, 2012),
((SELECT ID FROM EDITORIAL WHERE NAME = 'Anagrama'), 'El inquilino', 'Javier Cercas', 'Ficción', 208, TRUE, 1989),
((SELECT ID FROM EDITORIAL WHERE NAME = 'Alfaguara'), 'Retrato en sepia', 'Isabel Allende', 'Ficción', 394, TRUE, 2000),
((SELECT ID FROM EDITORIAL WHERE NAME = 'Tusquets Editores'), 'Queremos tanto a Glenda', 'Julio Cortázar', 'Cuentos', 168, TRUE, 1980),
((SELECT ID FROM EDITORIAL WHERE NAME = 'Editorial Anaya'), 'Novelas ejemplares', 'Miguel de Cervantes', 'Clásico', 496, TRUE, 1613),
((SELECT ID FROM EDITORIAL WHERE NAME = 'Ediciones SM'), 'Las brujas', 'Roald Dahl', 'Infantil', 208, TRUE, 1983),
((SELECT ID FROM EDITORIAL WHERE NAME = 'Editorial Santillana'), 'La conspiración', 'Dan Brown', 'Thriller', 589, TRUE, 2001),
((SELECT ID FROM EDITORIAL WHERE NAME = 'Espasa'), 'Insolación', 'Emilia Pardo Bazán', 'Realismo', 272, TRUE, 1889),
((SELECT ID FROM EDITORIAL WHERE NAME = 'Ediciones B'), 'El tiempo entre costuras', 'María Dueñas', 'Ficción histórica', 608, TRUE, 2009),
((SELECT ID FROM EDITORIAL WHERE NAME = 'RBA Libros'), 'En el blanco', 'Ken Follett', 'Thriller', 416, TRUE, 1996),
((SELECT ID FROM EDITORIAL WHERE NAME = 'Alianza Editorial'), 'Historia de la belleza', 'Umberto Eco', 'Ensayo', 438, TRUE, 2004),
((SELECT ID FROM EDITORIAL WHERE NAME = 'Seix Barral'), 'Los herederos de la tierra', 'Ildefonso Falcones', 'Ficción histórica', 768, TRUE, 2016),
((SELECT ID FROM EDITORIAL WHERE NAME = 'Debate'), 'Red Dragon', 'Thomas Harris', 'Thriller', 454, TRUE, 1981),
((SELECT ID FROM EDITORIAL WHERE NAME = 'Salamandra'), 'La despedida', 'Milan Kundera', 'Ficción', 224, TRUE, 1976),
((SELECT ID FROM EDITORIAL WHERE NAME = 'Ediciones Destino'), 'Subir a por aire', 'George Orwell', 'Ficción', 296, TRUE, 1939),
((SELECT ID FROM EDITORIAL WHERE NAME = 'Grijalbo'), 'Un día perfecto para el pez banana', 'J.D. Salinger', 'Cuento', 32, TRUE, 1948),
((SELECT ID FROM EDITORIAL WHERE NAME = 'Círculo de Lectores'), 'El olor de la guayaba', 'Gabriel García Márquez', 'Conversaciones', 156, TRUE, 1982),
((SELECT ID FROM EDITORIAL WHERE NAME = 'Ediciones Cátedra'), 'Mrs. Caldwell habla con su hijo', 'Camilo José Cela', 'Ficción epistolar', 304, TRUE, 1953),
((SELECT ID FROM EDITORIAL WHERE NAME = 'Editorial Crítica'), 'Uno y el universo', 'Ernesto Sabato', 'Ensayo', 168, TRUE, 1945),
((SELECT ID FROM EDITORIAL WHERE NAME = 'Paidós'), 'Casa tomada', 'Julio Cortázar', 'Cuento', 8, TRUE, 1946),
((SELECT ID FROM EDITORIAL WHERE NAME = 'Ariel'), 'Atlas', 'Jorge Luis Borges', 'Ensayo fotográfico', 192, TRUE, 1984),
((SELECT ID FROM EDITORIAL WHERE NAME = 'Taurus'), 'Travesuras de la niña mala', 'Mario Vargas Llosa', 'Ficción', 408, TRUE, 2006),
((SELECT ID FROM EDITORIAL WHERE NAME = 'Plataforma Editorial'), 'El juego del ángel', 'Carlos Ruiz Zafón', 'Misterio', 672, TRUE, 2008),
((SELECT ID FROM EDITORIAL WHERE NAME = 'Blackie Books'), 'La gran Marivían', 'Fernando Aramburu', 'Cuentos', 208, TRUE, 2000),
((SELECT ID FROM EDITORIAL WHERE NAME = 'Nórdica Libros'), 'El oro del rey', 'Arturo Pérez-Reverte', 'Aventuras', 336, TRUE, 2000),
((SELECT ID FROM EDITORIAL WHERE NAME = 'Páginas de Espuma'), 'Una comedia ligera', 'Eduardo Mendoza', 'Ficción', 496, TRUE, 1996),
((SELECT ID FROM EDITORIAL WHERE NAME = 'Pre-Textos'), 'Insolación', 'Carmen Laforet', 'Relatos', 256, TRUE, 1963),
((SELECT ID FROM EDITORIAL WHERE NAME = 'Editorial Acantilado'), 'El viejo y la muerte', 'Rafael Chirbes', 'Ficción', 384, TRUE, 2004),
((SELECT ID FROM EDITORIAL WHERE NAME = 'Impedimenta'), 'Cartes dItàlia', 'Josep Pla', 'Crónica de viaje', 352, TRUE, 1929),
((SELECT ID FROM EDITORIAL WHERE NAME = 'Sexto Piso'), 'Teniente Bravo', 'Juan Marsé', 'Ficción', 176, TRUE, 1987),
((SELECT ID FROM EDITORIAL WHERE NAME = 'Libros del Asteroide'), 'El disputado voto del señor Cayo', 'Miguel Delibes', 'Ficción', 192, TRUE, 1978),
((SELECT ID FROM EDITORIAL WHERE NAME = 'Galaxia Gutenberg'), 'Tots tres surten per lOzama', 'Mercè Rodoreda', 'Teatro', 128, TRUE, 1980),
((SELECT ID FROM EDITORIAL WHERE NAME = 'Ediciones Siruela'), 'La hoja roja', 'Miguel Delibes', 'Ficción', 256, TRUE, 1959),
((SELECT ID FROM EDITORIAL WHERE NAME = 'Minúscula'), 'Blanca vuela mañana', 'Dulce Chacón', 'Ficción', 192, TRUE, 1997),
((SELECT ID FROM EDITORIAL WHERE NAME = 'Navona Editorial'), 'Ella, maldita alma', 'Manuel Rivas', 'Ficción', 352, TRUE, 1999),
((SELECT ID FROM EDITORIAL WHERE NAME = 'Ediciones Obelisco'), 'Juegos de la edad tardía', 'Luis Landero', 'Ficción', 352, TRUE, 1989),
((SELECT ID FROM EDITORIAL WHERE NAME = 'Editorial Almuzara'), 'La noche de los tiempos', 'Antonio Muñoz Molina', 'Ficción', 736, TRUE, 2009),
((SELECT ID FROM EDITORIAL WHERE NAME = 'Ediciones Edhasa'), 'Foto de familia', 'Ignacio Martínez de Pisón', 'Ficción', 288, TRUE, 1998),
((SELECT ID FROM EDITORIAL WHERE NAME = 'Errata Naturae'), 'Independencia', 'Javier Cercas', 'Ficción', 384, TRUE, 2021),
((SELECT ID FROM EDITORIAL WHERE NAME = 'Funambulista'), 'Temblor', 'Rosa Montero', 'Ficción', 240, TRUE, 1990),
((SELECT ID FROM EDITORIAL WHERE NAME = 'Editorial Periférica'), 'Laura y Julio', 'Juan José Millás', 'Ficción', 256, TRUE, 2006),
((SELECT ID FROM EDITORIAL WHERE NAME = 'Caballo de Troya'), 'Mañana en la batalla piensa en mí', 'Javier Marías', 'Ficción', 464, TRUE, 1994),
((SELECT ID FROM EDITORIAL WHERE NAME = 'Duomo Ediciones'), 'Vida del fantasma', 'Javier Marías', 'Ensayo', 256, TRUE, 1995),
((SELECT ID FROM EDITORIAL WHERE NAME = 'Punto de Lectura'), 'Retrato de un hombre inmaduro', 'Luis Landero', 'Ficción', 272, TRUE, 2009),
((SELECT ID FROM EDITORIAL WHERE NAME = 'Editorial Kalandraka'), 'El pastel del diablo', 'Carmen Martín Gaite', 'Ensayo', 240, TRUE, 1985),
((SELECT ID FROM EDITORIAL WHERE NAME = 'Ediciones Maeva'), 'Nadie escucha', 'Julio Llamazares', 'Narrativa', 208, TRUE, 1995),
((SELECT ID FROM EDITORIAL WHERE NAME = 'Editorial Bruño'), 'La hermandad de la Sábana Santa', 'Julia Navarro', 'Thriller', 608, TRUE, 2004),
((SELECT ID FROM EDITORIAL WHERE NAME = 'Edelvives'), 'Mujer en el baño', 'Manuel Rivas', 'Cuentos', 192, TRUE, 1995),
((SELECT ID FROM EDITORIAL WHERE NAME = 'La Esfera de los Libros'), 'Las edades de Lulú', 'Almudena Grandes', 'Ficción', 288, TRUE, 1989),
((SELECT ID FROM EDITORIAL WHERE NAME = 'Penguin Random House'), 'La increíble y triste historia de la cándida Eréndira', 'Gabriel García Márquez', 'Relatos', 175, TRUE, 1972),
((SELECT ID FROM EDITORIAL WHERE NAME = 'Editorial Planeta'), 'El laberinto de los espíritus', 'Carlos Ruiz Zafón', 'Misterio', 976, TRUE, 2016),
((SELECT ID FROM EDITORIAL WHERE NAME = 'Anagrama'), 'El punto ciego', 'Javier Cercas', 'Ensayo', 176, TRUE, 2016),
((SELECT ID FROM EDITORIAL WHERE NAME = 'Alfaguara'), 'El reino del dragón de oro', 'Isabel Allende', 'Aventuras juvenil', 397, TRUE, 2003),
((SELECT ID FROM EDITORIAL WHERE NAME = 'Tusquets Editores'), 'Todos los fuegos el fuego', 'Julio Cortázar', 'Cuentos', 152, TRUE, 1966),
((SELECT ID FROM EDITORIAL WHERE NAME = 'Editorial Anaya'), 'El celoso extremeño', 'Miguel de Cervantes', 'Clásico', 72, TRUE, 1613),
((SELECT ID FROM EDITORIAL WHERE NAME = 'Ediciones SM'), 'Danny, el campeón del mundo', 'Roald Dahl', 'Infantil', 224, TRUE, 1975),
((SELECT ID FROM EDITORIAL WHERE NAME = 'Editorial Santillana'), 'La verdad del caso Savolta', 'Eduardo Mendoza', 'Misterio', 336, TRUE, 1975),
((SELECT ID FROM EDITORIAL WHERE NAME = 'Espasa'), 'El cisne de Vilamorta', 'Emilia Pardo Bazán', 'Ficción', 336, TRUE, 1885),
((SELECT ID FROM EDITORIAL WHERE NAME = 'Ediciones B'), 'Libro de notas', 'María Dueñas', 'Blog literario', 0, FALSE, 2024),
((SELECT ID FROM EDITORIAL WHERE NAME = 'RBA Libros'), 'El hombre de San Petersburgo', 'Ken Follett', 'Thriller histórico', 368, TRUE, 1982),
((SELECT ID FROM EDITORIAL WHERE NAME = 'Alianza Editorial'), 'Seis paseos por los bosques narrativos', 'Umberto Eco', 'Ensayo', 192, TRUE, 1994),
((SELECT ID FROM EDITORIAL WHERE NAME = 'Seix Barral'), 'Marina', 'Carlos Ruiz Zafón', 'Misterio', 312, TRUE, 1999),
((SELECT ID FROM EDITORIAL WHERE NAME = 'Debate'), 'El silencio de los inocentes', 'Thomas Harris', 'Thriller', 352, TRUE, 1988),
((SELECT ID FROM EDITORIAL WHERE NAME = 'Salamandra'), 'El vals de los adioses', 'Milan Kundera', 'Ficción', 144, TRUE, 1973),
((SELECT ID FROM EDITORIAL WHERE NAME = 'Ediciones Destino'), 'Recuerdos de la guerra de España', 'George Orwell', 'No ficción', 40, TRUE, 1942),
((SELECT ID FROM EDITORIAL WHERE NAME = 'Grijalbo'), 'Teddy', 'J.D. Salinger', 'Cuento', 36, TRUE, 1953),
((SELECT ID FROM EDITORIAL WHERE NAME = 'Círculo de Lectores'), 'Doce cuentos peregrinos', 'Gabriel García Márquez', 'Cuentos', 224, TRUE, 1992),
((SELECT ID FROM EDITORIAL WHERE NAME = 'Ediciones Cátedra'), 'Madera de boj', 'Camilo José Cela', 'Ficción', 416, TRUE, 1999),
((SELECT ID FROM EDITORIAL WHERE NAME = 'Editorial Crítica'), 'España en los diarios de mi vejez', 'Ernesto Sabato', 'Ensayo', 208, TRUE, 2004);