/**
 * Author:  Napoleon Avila Ochoa
 * Created: 04/12/2025
 */
DROP TABLE IF EXISTS BOOK;

CREATE TABLE IF NOT EXISTS BOOK (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    TITLE VARCHAR(255) NOT NULL,
    AUTHOR VARCHAR(255) NOT NULL,
    GENRE VARCHAR(150) NOT NULL,
    PAGES INT NOT NULL DEFAULT 1,
    ACTIVE BOOLEAN DEFAULT TRUE NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    PUBLICATION_YEAR INT
);


-- ============================================================
-- DATOS INICIALES: BOOK
-- ============================================================

INSERT INTO BOOK (TITLE, AUTHOR, GENRE, PAGES, ACTIVE, PUBLICATION_YEAR) VALUES
('Cien años de soledad', 'Gabriel García Márquez', 'FANTASY', 471, TRUE, 1967),
('El amor en los tiempos del cólera', 'Gabriel García Márquez', 'ROMANCE', 368, TRUE, 1985),
('La sombra del viento', 'Carlos Ruiz Zafón', 'MYSTERY', 576, TRUE, 2001),
('Marina', 'Carlos Ruiz Zafón', 'MYSTERY', 312, TRUE, 1999),
('Soldados de Salamina', 'Javier Cercas', 'HISTORICAL_FICTION', 215, TRUE, 2001),
('El impostor', 'Javier Cercas', 'FICTION', 432, TRUE, 2014),
('La casa de los espíritus', 'Isabel Allende', 'FANTASY', 433, TRUE, 1982),
('Paula', 'Isabel Allende', 'NON_FICTION', 368, TRUE, 1994),
('El juego del ángel', 'Carlos Ruiz Zafón', 'MYSTERY', 672, TRUE, 2008),
('Rayuela', 'Julio Cortázar', 'FICTION', 736, TRUE, 1963),
('Don Quijote de la Mancha', 'Miguel de Cervantes', 'CLASSIC', 863, TRUE, 1605),
('La Celestina', 'Fernando de Rojas', 'CLASSIC', 288, TRUE, 1499),
('El principito', 'Antoine de Saint-Exupéry', 'CHILDREN', 96, TRUE, 1943),
('Harry Potter y la piedra filosofal', 'J.K. Rowling', 'FANTASY', 254, TRUE, 1997),
('El código Da Vinci', 'Dan Brown', 'MYSTERY', 489, TRUE, 2003),
('Ángeles y demonios', 'Dan Brown', 'MYSTERY', 616, TRUE, 2000),
('La Regenta', 'Leopoldo Alas Clarín', 'CLASSIC', 789, TRUE, 1884),
('Fortunata y Jacinta', 'Benito Pérez Galdós', 'CLASSIC', 1056, TRUE, 1887),
('El tiempo entre costuras', 'María Dueñas', 'HISTORICAL_FICTION', 608, TRUE, 2009),
('La templanza', 'María Dueñas', 'HISTORICAL_FICTION', 688, TRUE, 2015),
('Los pilares de la Tierra', 'Ken Follett', 'HISTORICAL_FICTION', 1008, TRUE, 1989),
('Un mundo sin fin', 'Ken Follett', 'HISTORICAL_FICTION', 1120, TRUE, 2007),
('El nombre de la rosa', 'Umberto Eco', 'MYSTERY', 536, TRUE, 1980),
('El péndulo de Foucault', 'Umberto Eco', 'FICTION', 656, TRUE, 1988),
('La catedral del mar', 'Ildefonso Falcones', 'HISTORICAL_FICTION', 672, TRUE, 2006),
('Los herederos de la tierra', 'Ildefonso Falcones', 'HISTORICAL_FICTION', 768, TRUE, 2016),
('El silencio de los corderos', 'Thomas Harris', 'MYSTERY', 352, TRUE, 1988),
('Hannibal', 'Thomas Harris', 'MYSTERY', 486, TRUE, 1999),
('La insoportable levedad del ser', 'Milan Kundera', 'FICTION', 320, TRUE, 1984),
('La broma', 'Milan Kundera', 'FICTION', 352, TRUE, 1967),
('1984', 'George Orwell', 'SCIENCE_FICTION', 328, TRUE, 1949),
('Rebelión en la granja', 'George Orwell', 'FICTION', 152, TRUE, 1945),
('El guardián entre el centeno', 'J.D. Salinger', 'FICTION', 277, TRUE, 1951),
('Franny y Zooey', 'J.D. Salinger', 'FICTION', 201, TRUE, 1961),
('Crónica de una muerte anunciada', 'Gabriel García Márquez', 'FICTION', 120, TRUE, 1981),
('El coronel no tiene quien le escriba', 'Gabriel García Márquez', 'FICTION', 104, TRUE, 1961),
('La colmena', 'Camilo José Cela', 'CLASSIC', 336, TRUE, 1951),
('La familia de Pascual Duarte', 'Camilo José Cela', 'CLASSIC', 168, TRUE, 1942),
('El túnel', 'Ernesto Sabato', 'FICTION', 158, TRUE, 1948),
('Sobre héroes y tumbas', 'Ernesto Sabato', 'FICTION', 528, TRUE, 1961),
('Pedro Páramo', 'Juan Rulfo', 'FANTASY', 124, TRUE, 1955),
('El llano en llamas', 'Juan Rulfo', 'FICTION', 168, TRUE, 1953),
('Ficciones', 'Jorge Luis Borges', 'FICTION', 174, TRUE, 1944),
('El Aleph', 'Jorge Luis Borges', 'FICTION', 203, TRUE, 1949),
('La ciudad y los perros', 'Mario Vargas Llosa', 'FICTION', 408, TRUE, 1963),
('Conversación en La Catedral', 'Mario Vargas Llosa', 'FICTION', 731, TRUE, 1969),
('El laberinto de los espíritus', 'Carlos Ruiz Zafón', 'MYSTERY', 976, TRUE, 2016),
('El prisionero del cielo', 'Carlos Ruiz Zafón', 'MYSTERY', 448, TRUE, 2011),
('Patria', 'Fernando Aramburu', 'FICTION', 648, TRUE, 2016),
('Los vencejos', 'Fernando Aramburu', 'FICTION', 432, TRUE, 2021),
('El capitán Alatriste', 'Arturo Pérez-Reverte', 'ADVENTURE', 256, TRUE, 1996),
('La reina del sur', 'Arturo Pérez-Reverte', 'MYSTERY', 543, TRUE, 2002),
('La verdad sobre el caso Savolta', 'Eduardo Mendoza', 'MYSTERY', 336, TRUE, 1975),
('La ciudad de los prodigios', 'Eduardo Mendoza', 'HISTORICAL_FICTION', 544, TRUE, 1986),
('Nada', 'Carmen Laforet', 'FICTION', 288, TRUE, 1945),
('La mujer nueva', 'Carmen Laforet', 'FICTION', 368, TRUE, 1955),
('Crematorio', 'Rafael Chirbes', 'FICTION', 448, TRUE, 2007),
('En la orilla', 'Rafael Chirbes', 'FICTION', 432, TRUE, 2013),
('El cuaderno gris', 'Josep Pla', 'NON_FICTION', 928, TRUE, 1966),
('Viaje en autobús', 'Josep Pla', 'NON_FICTION', 288, TRUE, 1942),
('Últimas tardes con Teresa', 'Juan Marsé', 'FICTION', 464, TRUE, 1966),
('Si te dicen que caí', 'Juan Marsé', 'FICTION', 368, TRUE, 1973),
('El hereje', 'Miguel Delibes', 'HISTORICAL_FICTION', 576, TRUE, 1998),
('Los santos inocentes', 'Miguel Delibes', 'FICTION', 224, TRUE, 1981),
('La plaza del diamante', 'Mercè Rodoreda', 'FICTION', 232, TRUE, 1962),
('Mirall trencat', 'Mercè Rodoreda', 'FICTION', 528, TRUE, 1974),
('Cinco horas con Mario', 'Miguel Delibes', 'FICTION', 312, TRUE, 1966),
('El camino', 'Miguel Delibes', 'FICTION', 208, TRUE, 1950),
('La voz dormida', 'Dulce Chacón', 'HISTORICAL_FICTION', 456, TRUE, 2002),
('La viajera', 'Dulce Chacón', 'FICTION', 312, TRUE, 1995),
('El lápiz del carpintero', 'Manuel Rivas', 'HISTORICAL_FICTION', 248, TRUE, 1998),
('¿Qué me quieres, amor?', 'Manuel Rivas', 'FICTION', 224, TRUE, 1995),
('Beatus Ille', 'Antonio Muñoz Molina', 'FICTION', 368, TRUE, 1986),
('Plenilunio', 'Antonio Muñoz Molina', 'MYSTERY', 464, TRUE, 1997),
('El jinete polaco', 'Antonio Muñoz Molina', 'FICTION', 560, TRUE, 1991),
('Sefarad', 'Antonio Muñoz Molina', 'FICTION', 544, TRUE, 2001),
('Enterrar a los muertos', 'Ignacio Martínez de Pisón', 'NON_FICTION', 512, TRUE, 2005),
('El día de mañana', 'Ignacio Martínez de Pisón', 'FICTION', 464, TRUE, 2011),
('Anatomía de un instante', 'Javier Cercas', 'NON_FICTION', 456, TRUE, 2009),
('Terra Alta', 'Javier Cercas', 'MYSTERY', 392, TRUE, 2019),
('La ridícula idea de no volver a verte', 'Rosa Montero', 'ESSAY', 224, TRUE, 2013),
('La carne', 'Rosa Montero', 'FICTION', 368, TRUE, 2016),
('El desorden de tu nombre', 'Juan José Millás', 'FICTION', 200, TRUE, 1988),
('La soledad era esto', 'Juan José Millás', 'FICTION', 224, TRUE, 1990),
('Corazón tan blanco', 'Javier Marías', 'FICTION', 336, TRUE, 1992),
('Todas las almas', 'Javier Marías', 'FICTION', 368, TRUE, 1989),
('Mañana en la batalla piensa en mí', 'Javier Marías', 'FICTION', 464, TRUE, 1994),
('Los enamoramientos', 'Javier Marías', 'FICTION', 416, TRUE, 2011),
('Juegos de la edad tardía', 'Luis Landero', 'FICTION', 352, TRUE, 1989),
('Caballeros de fortuna', 'Luis Landero', 'FICTION', 480, TRUE, 1994),
('El cuarto de atrás', 'Carmen Martín Gaite', 'FICTION', 208, TRUE, 1978),
('Nubosidad variable', 'Carmen Martín Gaite', 'FICTION', 304, TRUE, 1992),
('La lluvia amarilla', 'Julio Llamazares', 'FICTION', 176, TRUE, 1988),
('La noche de los tiempos', 'Antonio Muñoz Molina', 'FICTION', 736, TRUE, 2009),
('Dime quién soy', 'Julia Navarro', 'HISTORICAL_FICTION', 1120, TRUE, 2010),
('Dispara, yo ya estoy muerto', 'Julia Navarro', 'HISTORICAL_FICTION', 864, TRUE, 2013),
('La lengua de las mariposas', 'Manuel Rivas', 'FICTION', 160, TRUE, 1996),
('El sur', 'Adelaida García Morales', 'FICTION', 96, TRUE, 1985),
('Inés y la alegría', 'Almudena Grandes', 'HISTORICAL_FICTION', 672, TRUE, 2010),
('El otoño del patriarca', 'Gabriel García Márquez', 'FICTION', 271, TRUE, 1975),
('El príncipe de la niebla', 'Carlos Ruiz Zafón', 'FANTASY', 224, TRUE, 1993),
('El inquilino', 'Javier Cercas', 'FICTION', 208, TRUE, 1989),
('Eva Luna', 'Isabel Allende', 'FICTION', 288, TRUE, 1987),
('Bestiario', 'Julio Cortázar', 'FICTION', 168, TRUE, 1951),
('Lazarillo de Tormes', 'Anónimo', 'CLASSIC', 128, TRUE, 1554),
('El león, la bruja y el armario', 'C.S. Lewis', 'FANTASY', 208, TRUE, 1950),
('Inferno', 'Dan Brown', 'MYSTERY', 461, TRUE, 2013),
('Los pazos de Ulloa', 'Emilia Pardo Bazán', 'CLASSIC', 336, TRUE, 1886),
('Misión Olvido', 'María Dueñas', 'FICTION', 624, TRUE, 2012),
('La caída de los gigantes', 'Ken Follett', 'HISTORICAL_FICTION', 1008, TRUE, 2010),
('La isla del día de antes', 'Umberto Eco', 'HISTORICAL_FICTION', 528, TRUE, 1994),
('La mano de Fátima', 'Ildefonso Falcones', 'HISTORICAL_FICTION', 736, TRUE, 2009),
('Dragón Rojo', 'Thomas Harris', 'MYSTERY', 454, TRUE, 1981),
('La identidad', 'Milan Kundera', 'FICTION', 168, TRUE, 1998),
('Homenaje a Cataluña', 'George Orwell', 'NON_FICTION', 248, TRUE, 1938),
('Nueve cuentos', 'J.D. Salinger', 'FICTION', 198, TRUE, 1953),
('Del amor y otros demonios', 'Gabriel García Márquez', 'FICTION', 147, TRUE, 1994),
('Mazurca para dos muertos', 'Camilo José Cela', 'FICTION', 304, TRUE, 1983),
('Informe sobre ciegos', 'Ernesto Sabato', 'FICTION', 256, TRUE, 1961),
('El gallo de oro', 'Juan Rulfo', 'FICTION', 96, TRUE, 1980),
('El libro de arena', 'Jorge Luis Borges', 'FICTION', 176, TRUE, 1975),
('La tía Julia y el escribidor', 'Mario Vargas Llosa', 'FICTION', 448, TRUE, 1977),
('El palacio de la medianoche', 'Carlos Ruiz Zafón', 'FANTASY', 288, TRUE, 1994),
('Años lentos', 'Fernando Aramburu', 'FICTION', 336, TRUE, 2012),
('El Club Dumas', 'Arturo Pérez-Reverte', 'MYSTERY', 384, TRUE, 1993),
('Sin noticias de Gurb', 'Eduardo Mendoza', 'FICTION', 144, TRUE, 1991),
('La isla y los demonios', 'Carmen Laforet', 'FICTION', 304, TRUE, 1952),
('La larga marcha', 'Rafael Chirbes', 'FICTION', 520, TRUE, 1996),
('El pasajero', 'Josep Pla', 'FICTION', 256, TRUE, 1925),
('El embrujo de Shanghai', 'Juan Marsé', 'FICTION', 416, TRUE, 1993),
('Señora de rojo sobre fondo gris', 'Miguel Delibes', 'FICTION', 176, TRUE, 1991),
('La calle de las camelias', 'Mercè Rodoreda', 'FICTION', 256, TRUE, 1966),
('Las ratas', 'Miguel Delibes', 'FICTION', 192, TRUE, 1962),
('Algún amor que no mate', 'Dulce Chacón', 'OTHER', 96, TRUE, 1996),
('Los libros arden mal', 'Manuel Rivas', 'FICTION', 656, TRUE, 2006),
('El invierno en Lisboa', 'Antonio Muñoz Molina', 'FICTION', 256, TRUE, 1987),
('Sepharad', 'Antonio Muñoz Molina', 'FICTION', 544, TRUE, 2001),
('Carreteras secundarias', 'Ignacio Martínez de Pisón', 'FICTION', 256, TRUE, 1996),
('El vientre de la ballena', 'Javier Cercas', 'FICTION', 144, TRUE, 1997),
('Lágrimas en la lluvia', 'Rosa Montero', 'SCIENCE_FICTION', 416, TRUE, 2011),
('Papel mojado', 'Juan José Millás', 'FICTION', 272, TRUE, 1983),
('Tu rostro mañana', 'Javier Marías', 'FICTION', 1504, TRUE, 2002),
('Negra espalda del tiempo', 'Javier Marías', 'ESSAY', 400, TRUE, 1998),
('Hoy, Júpiter', 'Luis Landero', 'FICTION', 272, TRUE, 2007),
('Caperucita en Manhattan', 'Carmen Martín Gaite', 'CHILDREN', 208, TRUE, 1990),
('Luna de lobos', 'Julio Llamazares', 'FICTION', 192, TRUE, 1985),
('Hermanos de sangre', 'Julia Navarro', 'HISTORICAL_FICTION', 928, TRUE, 2015),
('El silencio roto', 'Montserrat del Amo', 'FICTION', 288, TRUE, 1997),
('El corazón helado', 'Almudena Grandes', 'FICTION', 1104, TRUE, 2007),
('Noticia de un secuestro', 'Gabriel García Márquez', 'NON_FICTION', 315, TRUE, 1996),
('Las luces de septiembre', 'Carlos Ruiz Zafón', 'FANTASY', 256, TRUE, 1995),
('Outlaws', 'Javier Cercas', 'FICTION', 224, TRUE, 2022),
('De amor y de sombra', 'Isabel Allende', 'FICTION', 271, TRUE, 1984),
('Final del juego', 'Julio Cortázar', 'FICTION', 232, TRUE, 1956),
('La vida del Buscón', 'Francisco de Quevedo', 'CLASSIC', 256, TRUE, 1626),
('Matilda', 'Roald Dahl', 'CHILDREN', 240, TRUE, 1988),
('El símbolo perdido', 'Dan Brown', 'MYSTERY', 509, TRUE, 2009),
('La madre naturaleza', 'Emilia Pardo Bazán', 'CLASSIC', 456, TRUE, 1887),
('Las hijas del Capitán', 'María Dueñas', 'HISTORICAL_FICTION', 784, TRUE, 2018),
('El invierno del mundo', 'Ken Follett', 'HISTORICAL_FICTION', 1024, TRUE, 2012),
('Baudolino', 'Umberto Eco', 'HISTORICAL_FICTION', 568, TRUE, 2000),
('El pintor de almas', 'Ildefonso Falcones', 'HISTORICAL_FICTION', 688, TRUE, 2019),
('Cari Mora', 'Thomas Harris', 'MYSTERY', 304, TRUE, 2019),
('La inmortalidad', 'Milan Kundera', 'FICTION', 384, TRUE, 1990),
('El camino de Wigan Pier', 'George Orwell', 'NON_FICTION', 264, TRUE, 1937),
('Levantad, carpinteros, la viga del tejado', 'J.D. Salinger', 'FICTION', 256, TRUE, 1963),
('La mala hora', 'Gabriel García Márquez', 'FICTION', 183, TRUE, 1962),
('Cristo versus Arizona', 'Camilo José Cela', 'FICTION', 192, TRUE, 1988),
('Abbadón el exterminador', 'Ernesto Sabato', 'FICTION', 543, TRUE, 1974),
('Carta a una señorita en París', 'Julio Cortázar', 'FICTION', 24, TRUE, 1951),
('Historia universal de la infamia', 'Jorge Luis Borges', 'FICTION', 168, TRUE, 1935),
('Pantaleón y las visitadoras', 'Mario Vargas Llosa', 'FICTION', 320, TRUE, 1973),
('Fuegos con limón', 'Fernando Aramburu', 'FICTION', 224, TRUE, 1996),
('La tabla de Flandes', 'Arturo Pérez-Reverte', 'MYSTERY', 384, TRUE, 1990),
('El misterio de la cripta embrujada', 'Eduardo Mendoza', 'MYSTERY', 224, TRUE, 1979),
('Al volver la esquina', 'Carmen Laforet', 'FICTION', 448, TRUE, 2004),
('Mimoun', 'Rafael Chirbes', 'FICTION', 272, TRUE, 1988),
('Notes disperses', 'Josep Pla', 'ESSAY', 384, TRUE, 1969),
('Rabos de lagartija', 'Juan Marsé', 'FICTION', 368, TRUE, 2000),
('Diario de un jubilado', 'Miguel Delibes', 'NON_FICTION', 272, TRUE, 1995),
('Jardín umbría', 'Mercè Rodoreda', 'FICTION', 240, TRUE, 1989),
('Parábola del náufrago', 'Miguel Delibes', 'FICTION', 208, TRUE, 1969),
('Contra el desprestigio de la altura', 'Dulce Chacón', 'OTHER', 80, TRUE, 1995),
('En salvaje compañía', 'Manuel Rivas', 'FICTION', 288, TRUE, 1994),
('Beltenebros', 'Antonio Muñoz Molina', 'MYSTERY', 208, TRUE, 1989),
('Carlota Fainberg', 'Antonio Muñoz Molina', 'FICTION', 256, TRUE, 1999),
('El tiempo de las mujeres', 'Ignacio Martínez de Pisón', 'FICTION', 288, TRUE, 2003),
('Las leyes de la frontera', 'Javier Cercas', 'FICTION', 384, TRUE, 2012),
('El peso del corazón', 'Rosa Montero', 'SCIENCE_FICTION', 448, TRUE, 2015),
('Dos mujeres en Praga', 'Juan José Millás', 'FICTION', 272, TRUE, 2002),
('Una comedia ligera', 'Eduardo Mendoza', 'FICTION', 496, TRUE, 1996),
('Cuando los tontos manden', 'Javier Marías', 'ESSAY', 336, TRUE, 2013),
('Entre líneas: el cuento o la vida', 'Luis Landero', 'ESSAY', 272, TRUE, 2001),
('Irse de casa', 'Carmen Martín Gaite', 'FICTION', 304, TRUE, 1998),
('Distintas formas de mirar el agua', 'Julio Llamazares', 'FICTION', 176, TRUE, 2015),
('De ninguna parte', 'Julia Navarro', 'FICTION', 768, TRUE, 2024),
('Todo lo que era sólido', 'Antonio Muñoz Molina', 'ESSAY', 240, TRUE, 2013),
('Los besos en el pan', 'Almudena Grandes', 'FICTION', 368, TRUE, 2015),
('Vivir para contarla', 'Gabriel García Márquez', 'NON_FICTION', 569, TRUE, 2002),
('La velocidad de la luz', 'Javier Cercas', 'FICTION', 432, TRUE, 2005),
('El plan infinito', 'Isabel Allende', 'FICTION', 448, TRUE, 1991),
('Historias de cronopios y de famas', 'Julio Cortázar', 'FICTION', 152, TRUE, 1962),
('Rinconete y Cortadillo', 'Miguel de Cervantes', 'CLASSIC', 96, TRUE, 1613),
('Charlie y la fábrica de chocolate', 'Roald Dahl', 'CHILDREN', 176, TRUE, 1964),
('Origen', 'Dan Brown', 'MYSTERY', 461, TRUE, 2017),
('La tribuna', 'Emilia Pardo Bazán', 'CLASSIC', 272, TRUE, 1883),
('Sira', 'María Dueñas', 'HISTORICAL_FICTION', 800, TRUE, 2021),
('El umbral de la eternidad', 'Ken Follett', 'HISTORICAL_FICTION', 1152, TRUE, 2014),
('Número cero', 'Umberto Eco', 'FICTION', 224, TRUE, 2015),
('Una historia española', 'Ildefonso Falcones', 'HISTORICAL_FICTION', 800, TRUE, 2022),
('El silencio de los corderos 2', 'Thomas Harris', 'MYSTERY', 368, TRUE, 2006),
('La lentitud', 'Milan Kundera', 'FICTION', 160, TRUE, 1995),
('Los días de Birmania', 'George Orwell', 'FICTION', 312, TRUE, 1934),
('Seymour: una introducción', 'J.D. Salinger', 'FICTION', 96, TRUE, 1963),
('Ojos de perro azul', 'Gabriel García Márquez', 'FICTION', 152, TRUE, 1947),
('El asesinato del perdedor', 'Camilo José Cela', 'FICTION', 288, TRUE, 1994),
('Antes del fin', 'Ernesto Sabato', 'ESSAY', 224, TRUE, 1998),
('Axolotl', 'Julio Cortázar', 'FICTION', 16, TRUE, 1956),
('El hacedor', 'Jorge Luis Borges', 'OTHER', 168, TRUE, 1960),
('El sueño del celta', 'Mario Vargas Llosa', 'HISTORICAL_FICTION', 456, TRUE, 2010),
('El vigilante del fiordo', 'Fernando Aramburu', 'FICTION', 320, TRUE, 2016),
('Territorio Comanche', 'Arturo Pérez-Reverte', 'FICTION', 208, TRUE, 1994),
('El año del diluvio', 'Eduardo Mendoza', 'FICTION', 336, TRUE, 1992),
('Mis páginas mejores', 'Carmen Laforet', 'OTHER', 288, TRUE, 1956),
('Paris-Austerlitz', 'Rafael Chirbes', 'FICTION', 368, TRUE, 2016),
('Un señor de Barcelona', 'Josep Pla', 'FICTION', 304, TRUE, 1951),
('La muchacha de las bragas de oro', 'Juan Marsé', 'FICTION', 304, TRUE, 1978),
('Diario de un cazador', 'Miguel Delibes', 'FICTION', 288, TRUE, 1955),
('Viajes y flores', 'Mercè Rodoreda', 'FICTION', 192, TRUE, 1980),
('Mi idolatrado hijo Sisí', 'Miguel Delibes', 'FICTION', 240, TRUE, 1953),
('Querrán ponerle nombre', 'Dulce Chacón', 'OTHER', 88, TRUE, 1992),
('Todo es silencio', 'Manuel Rivas', 'MYSTERY', 304, TRUE, 2010),
('Un Robinson urbano', 'Antonio Muñoz Molina', 'ESSAY', 256, TRUE, 1993),
('Ardor guerrero', 'Antonio Muñoz Molina', 'FICTION', 256, TRUE, 1995),
('El fin de los buenos tiempos', 'Ignacio Martínez de Pisón', 'FICTION', 352, TRUE, 1994),
('Independencia', 'Javier Cercas', 'FICTION', 384, TRUE, 2021),
('Historia del Rey Transparente', 'Rosa Montero', 'HISTORICAL_FICTION', 400, TRUE, 2005),
('El mundo', 'Juan José Millás', 'FICTION', 240, TRUE, 2007),
('Berta Isla', 'Javier Marías', 'FICTION', 528, TRUE, 2017),
('Salvajes y sentimentales', 'Javier Marías', 'ESSAY', 272, TRUE, 2000),
('El guitarrista', 'Luis Landero', 'FICTION', 336, TRUE, 2002),
('Lo raro es vivir', 'Carmen Martín Gaite', 'ESSAY', 336, TRUE, 1996),
('Escenas de cine mudo', 'Julio Llamazares', 'FICTION', 208, TRUE, 1994),
('Tú no matarás', 'Julia Navarro', 'MYSTERY', 960, TRUE, 2018),
('La tierra convulsa', 'Manuel Rivas', 'FICTION', 304, TRUE, 2017),
('Atlas de geografía humana', 'Almudena Grandes', 'FICTION', 464, TRUE, 1998),
('12 cuentos peregrinos', 'Gabriel García Márquez', 'FICTION', 224, TRUE, 1992),
('La niebla', 'Carlos Ruiz Zafón', 'FICTION', 160, TRUE, 1993),
('El móvil', 'Javier Cercas', 'FICTION', 96, TRUE, 1987),
('Hija de la fortuna', 'Isabel Allende', 'HISTORICAL_FICTION', 399, TRUE, 1999),
('Octaedro', 'Julio Cortázar', 'FICTION', 168, TRUE, 1974),
('El coloquio de los perros', 'Miguel de Cervantes', 'CLASSIC', 112, TRUE, 1613),
('James y el melocotón gigante', 'Roald Dahl', 'CHILDREN', 176, TRUE, 1961),
('Fortaleza digital', 'Dan Brown', 'MYSTERY', 448, TRUE, 1998),
('Un viaje de novios', 'Emilia Pardo Bazán', 'FICTION', 288, TRUE, 1881),
('La Reina descalza', 'María Dueñas', 'HISTORICAL_FICTION', 656, TRUE, 2013),
('Noche sobre las aguas', 'Ken Follett', 'MYSTERY', 464, TRUE, 1991),
('El cementerio de Praga', 'Umberto Eco', 'HISTORICAL_FICTION', 560, TRUE, 2010),
('La luz de la noche', 'Ildefonso Falcones', 'HISTORICAL_FICTION', 672, TRUE, 2023),
('Black Sunday', 'Thomas Harris', 'MYSTERY', 318, TRUE, 1975),
('El libro de la risa y el olvido', 'Milan Kundera', 'FICTION', 288, TRUE, 1979),
('La hija del clérigo', 'George Orwell', 'FICTION', 320, TRUE, 1935),
('Hapworth 16, 1924', 'J.D. Salinger', 'FICTION', 128, TRUE, 1965),
('La hojarasca', 'Gabriel García Márquez', 'FICTION', 145, TRUE, 1955),
('Oficio de tinieblas 5', 'Camilo José Cela', 'FICTION', 224, TRUE, 1973),
('Hombres y engranajes', 'Ernesto Sabato', 'ESSAY', 192, TRUE, 1951),
('La noche boca arriba', 'Julio Cortázar', 'FICTION', 12, TRUE, 1956),
('Los conjurados', 'Jorge Luis Borges', 'OTHER', 96, TRUE, 1985),
('La fiesta del Chivo', 'Mario Vargas Llosa', 'HISTORICAL_FICTION', 517, TRUE, 2000),
('Rosa de fuego', 'Carlos Ruiz Zafón', 'MYSTERY', 144, TRUE, 2012),
('Autorretrato sin mí', 'Fernando Aramburu', 'ESSAY', 288, TRUE, 2018),
('Limpieza de sangre', 'Arturo Pérez-Reverte', 'ADVENTURE', 304, TRUE, 1997),
('Mauricio o las elecciones primarias', 'Eduardo Mendoza', 'FICTION', 224, TRUE, 2006),
('La llamada', 'Carmen Laforet', 'FICTION', 368, TRUE, 1954),
('Los viejos amigos', 'Rafael Chirbes', 'FICTION', 256, TRUE, 2003),
('Homenots', 'Josep Pla', 'NON_FICTION', 416, TRUE, 1969),
('Un día volveré', 'Juan Marsé', 'FICTION', 336, TRUE, 1982),
('La mortaja', 'Miguel Delibes', 'FICTION', 208, TRUE, 1970),
('Semblanza de Barcelona', 'Mercè Rodoreda', 'ESSAY', 128, TRUE, 1967),
('Vivir al día', 'Miguel Delibes', 'ESSAY', 336, TRUE, 1985),
('Las palabras de la piedra', 'Dulce Chacón', 'OTHER', 104, TRUE, 1993),
('La mano del emigrante', 'Manuel Rivas', 'FICTION', 240, TRUE, 2000),
('Ventanas de Manhattan', 'Antonio Muñoz Molina', 'ESSAY', 288, TRUE, 2004),
('La disciplina de la vanidad', 'Antonio Muñoz Molina', 'ESSAY', 304, TRUE, 1996),
('Alguien te observa', 'Ignacio Martínez de Pisón', 'MYSTERY', 336, TRUE, 2007),
('El castillo de Barbazul', 'Javier Cercas', 'ESSAY', 192, TRUE, 2007),
('Instrucciones para salvar el mundo', 'Rosa Montero', 'FICTION', 352, TRUE, 2008),
('El orden alfabético', 'Juan José Millás', 'FICTION', 224, TRUE, 1998),
('Tomás Nevinson', 'Javier Marías', 'FICTION', 624, TRUE, 2021),
('Pasiones pasadas', 'Javier Marías', 'ESSAY', 448, TRUE, 1991),
('La vida negociable', 'Luis Landero', 'FICTION', 368, TRUE, 2017),
('La búsqueda de interlocutor', 'Carmen Martín Gaite', 'ESSAY', 256, TRUE, 1973),
('El cielo de Madrid', 'Julio Llamazares', 'FICTION', 192, TRUE, 2005),
('Historia de un canalla', 'Julia Navarro', 'FICTION', 832, TRUE, 2016),
('El periodismo es un cuento', 'Manuel Rivas', 'ESSAY', 280, TRUE, 1997),
('Castillos de cartón', 'Almudena Grandes', 'FICTION', 624, TRUE, 2004),
('Relato de un náufrago', 'Gabriel García Márquez', 'NON_FICTION', 127, TRUE, 1970),
('El vuelo del ángel', 'Carlos Ruiz Zafón', 'OTHER', 256, TRUE, 2012),
('Retrato en sepia', 'Isabel Allende', 'FICTION', 394, TRUE, 2000),
('Queremos tanto a Glenda', 'Julio Cortázar', 'FICTION', 168, TRUE, 1980),
('Novelas ejemplares', 'Miguel de Cervantes', 'CLASSIC', 496, TRUE, 1613),
('Las brujas', 'Roald Dahl', 'CHILDREN', 208, TRUE, 1983),
('La conspiración', 'Dan Brown', 'MYSTERY', 589, TRUE, 2001),
('Insolación', 'Emilia Pardo Bazán', 'CLASSIC', 272, TRUE, 1889),
('En el blanco', 'Ken Follett', 'MYSTERY', 416, TRUE, 1996),
('Historia de la belleza', 'Umberto Eco', 'ESSAY', 438, TRUE, 2004),
('Red Dragon', 'Thomas Harris', 'MYSTERY', 454, TRUE, 1981),
('La despedida', 'Milan Kundera', 'FICTION', 224, TRUE, 1976),
('Subir a por aire', 'George Orwell', 'FICTION', 296, TRUE, 1939),
('Un día perfecto para el pez banana', 'J.D. Salinger', 'FICTION', 32, TRUE, 1948),
('El olor de la guayaba', 'Gabriel García Márquez', 'NON_FICTION', 156, TRUE, 1982),
('Mrs. Caldwell habla con su hijo', 'Camilo José Cela', 'FICTION', 304, TRUE, 1953),
('Uno y el universo', 'Ernesto Sabato', 'ESSAY', 168, TRUE, 1945),
('Casa tomada', 'Julio Cortázar', 'FICTION', 8, TRUE, 1946),
('Atlas', 'Jorge Luis Borges', 'ESSAY', 192, TRUE, 1984),
('Travesuras de la niña mala', 'Mario Vargas Llosa', 'FICTION', 408, TRUE, 2006),
('La gran Marivían', 'Fernando Aramburu', 'FICTION', 208, TRUE, 2000),
('El oro del rey', 'Arturo Pérez-Reverte', 'ADVENTURE', 336, TRUE, 2000),
('Insolación', 'Carmen Laforet', 'FICTION', 256, TRUE, 1963),
('El viejo y la muerte', 'Rafael Chirbes', 'FICTION', 384, TRUE, 2004),
('Cartes dItàlia', 'Josep Pla', 'NON_FICTION', 352, TRUE, 1929),
('Teniente Bravo', 'Juan Marsé', 'FICTION', 176, TRUE, 1987),
('El disputado voto del señor Cayo', 'Miguel Delibes', 'FICTION', 192, TRUE, 1978),
('Tots tres surten per lOzama', 'Mercè Rodoreda', 'OTHER', 128, TRUE, 1980),
('La hoja roja', 'Miguel Delibes', 'FICTION', 256, TRUE, 1959),
('Blanca vuela mañana', 'Dulce Chacón', 'FICTION', 192, TRUE, 1997),
('Ella, maldita alma', 'Manuel Rivas', 'FICTION', 352, TRUE, 1999),
('Foto de familia', 'Ignacio Martínez de Pisón', 'FICTION', 288, TRUE, 1998),
('Temblor', 'Rosa Montero', 'FICTION', 240, TRUE, 1990),
('Laura y Julio', 'Juan José Millás', 'FICTION', 256, TRUE, 2006),
('Vida del fantasma', 'Javier Marías', 'ESSAY', 256, TRUE, 1995),
('Retrato de un hombre inmaduro', 'Luis Landero', 'FICTION', 272, TRUE, 2009),
('El pastel del diablo', 'Carmen Martín Gaite', 'ESSAY', 240, TRUE, 1985),
('Nadie escucha', 'Julio Llamazares', 'FICTION', 208, TRUE, 1995),
('La hermandad de la Sábana Santa', 'Julia Navarro', 'MYSTERY', 608, TRUE, 2004),
('Mujer en el baño', 'Manuel Rivas', 'FICTION', 192, TRUE, 1995),
('Las edades de Lulú', 'Almudena Grandes', 'FICTION', 288, TRUE, 1989),
('La increíble y triste historia de la cándida Eréndira', 'Gabriel García Márquez', 'FICTION', 175, TRUE, 1972),
('El punto ciego', 'Javier Cercas', 'ESSAY', 176, TRUE, 2016),
('El reino del dragón de oro', 'Isabel Allende', 'ADVENTURE', 397, TRUE, 2003),
('Todos los fuegos el fuego', 'Julio Cortázar', 'FICTION', 152, TRUE, 1966),
('El celoso extremeño', 'Miguel de Cervantes', 'CLASSIC', 72, TRUE, 1613),
('Danny, el campeón del mundo', 'Roald Dahl', 'CHILDREN', 224, TRUE, 1975),
('La verdad del caso Savolta', 'Eduardo Mendoza', 'MYSTERY', 336, TRUE, 1975),
('El cisne de Vilamorta', 'Emilia Pardo Bazán', 'FICTION', 336, TRUE, 1885),
('Libro de notas', 'María Dueñas', 'OTHER', 1, FALSE, 2024),
('El hombre de San Petersburgo', 'Ken Follett', 'MYSTERY', 368, TRUE, 1982),
('Seis paseos por los bosques narrativos', 'Umberto Eco', 'ESSAY', 192, TRUE, 1994),
('El silencio de los inocentes', 'Thomas Harris', 'MYSTERY', 352, TRUE, 1988),
('El vals de los adioses', 'Milan Kundera', 'FICTION', 144, TRUE, 1973),
('Recuerdos de la guerra de España', 'George Orwell', 'NON_FICTION', 40, TRUE, 1942),
('Teddy', 'J.D. Salinger', 'FICTION', 36, TRUE, 1953),
('Doce cuentos peregrinos', 'Gabriel García Márquez', 'FICTION', 224, TRUE, 1992),
('Madera de boj', 'Camilo José Cela', 'FICTION', 416, TRUE, 1999),
('España en los diarios de mi vejez', 'Ernesto Sabato', 'ESSAY', 208, TRUE, 2004);